define(
{
    "m_home": "Inicio",
    "m_admin": "Admin",
    "m_tm": "Formulários",
    "m_analysis": "Análises",
    "m_reports": "Relatórios",
    "m_reports_def": "Relatórios Padrão",
    "m_reports_org": "Relatórios Organizacionais",
    "m_reports_leg": "Relatórios Herdados",
    "m_reports_new": "Novos Relatórios",
    "m_refresh": "Atualizar",
    "m_email_unsent": "Email não enviado",
    "m_export": "Exportar",
    "m_export_media": "Exportar com Media",
    "m_backup": "Backup",
    "m_backup_media": "Backup com Media",
    "m_discuss": "Opinião",
    "m_modify": "Modificar",
    "m_web_forms": "Formulários On-Line",
    "m_docs": "Documentação",
    "m_monitor": "Monitorização",
    "m_user": "Utilizadores",
    "m_assign": "Tarefas",
    "m_query": "Queries",
    "m_help": "Ajuda",
    "m_train": "Treinando",
    "m_forgot_password": "Recuperar Palavra-Chave",
    "m_register": "Criar Conta",
    "m_locations": "Locais",
    "m_section": "Secção",
    "m_notify": "Notificações",
    "m_view": "Visualizar",
    "m_attach": "Carregar Anexos",
    "m_modules": "Módulos",
    "m_open": "Abrir",
    "m_new": "Novo",
    "m_import": "Importar",
    "m_calculations": "Cálculos",
    "m_resources": "Recursos Partilhados",
    "m_review": "Rever",
    "m_mf": "Questionários geridos",
    "m_br": "Visualizar resultados",
    "m_manage": "Gerir",
    "m_dash": "Dashboard",
    "m_console": "Console",
    "m_s_m_f": "Configurar questionários geridos",
    "m_task_m": "Gestão de tarefas",
    "m_user_profile": "Perfil de utilizador",
    "m_login": "Login",
    "m_logs": "Logs",
    "m_info": "Info",
    "m_os": "Supervisão",
    "m_billing": "Faturamento",
    "m_rates": "Taxas",
    "m_billing_server": "Faturamento do Servidor",
    "m_billing_orgs": "Faturamento de Organizações",
    "m_bill_level": "Nível da Conta",
    "ss_welcome": "Bem Vindo ao Servidor SMAP Versão:",
    "ss_welcome2": "Alterações nesta versão",
    "ss_ft": "Descarregar Field Task",
    "ss_su": "Descarregar Smap Uploader",
    "c_api_builder": "Construtor de API",
    "c_api": "API",
    "c_links": "Links",
    "c_audit": "Audit",
    "c_url": "URL",
    "c_apply": "Aplicar",
    "c_desc": "Descrição",
    "c_default": "Padrão",
    "c_project": "Projeto",
    "c_forms": "Formulários",
    "c_form": "Questionário",
    "c_forward": "Reencaminhar",
    "c_forwarded": "Reencaminhado",
    "c_name": "Nome",
    "c_company_name": "Nome Empresa",
    "c_company_addr": "Endereço da empresa",
    "c_company_phone": "Telefone da empresa",
    "c_company_email": "E-mail da empresa",
    "c_type": "Tipo",
    "c_file": "Ficheiro",
    "c_host": "Servidor",
    "c_rank": "Rank",
    "c_user": "Utilizador",
    "c_vertical": "Vertical",
    "c_projects": "Projectos",
    "c_email": "Correio Electrónico",
    "c_emails": "Emails",
    "c_sms": "SMS",
    "c_document": "Documento",
    "c_twitter": "Twitter",
    "c_lang": "Linguagem",
    "c_langs": "Idiomas",
    "c_pulldata": "Puxar dados",
    "c_pulldata_r": "Repetir puxar dados",
    "c_orientation": "Orientação",
    "c_password": "Palavra-Chave",
    "c_c_p": "Confirme Palavra-Chave",
    "c_c_d": "Confirmar Apagar",
    "c_r_p": "Limpar Palavra-Chave",
    "c_reset": "Reset",
    "c_en": "Ativar",
    "c_dis": "Desativar",
    "c_loc_f": "Form. Local:",
    "c_rem_f": "Form. Remoto",
    "c_rem_u": "Utilizador Remoto",
    "c_enabled": "Ativo",
    "c_edit": "Editar",
    "c_del": "Eliminar",
    "c_undel": "Desfazer Apagar",
    "c_del_data": "Apagar Dados",
    "c_res_data": "Restaurar Dados",
    "c_download": "Descarregar",
    "c_upload": "Enviar",
    "c_done": "Efetuado",
    "c_cancel": "Cancelar",
    "c_save": "Gravar",
    "c_saved": "Salvo",
    "c_submit": "Submeter",
    "c_submitted": "Submetido",
    "c_test": "Testar",
    "c_validate": "Validar",
    "c_close": "Fechar",
    "c_likert": "Likert",
    "c_logout": "Terminar Sessão",
    "c_block": "Bloquear",
    "c_blocked": "Bloqueado",
    "c_graph": "Gráfico",
    "c_map": "Mapa",
    "c_chart": "Gráfico",
    "c_charts": "Gráficos",
    "c_maps": "Mapas",
    "c_map_layers": "Camadas do Mapa",
    "c_table": "Tabela",
    "c_tables": "Tabelas",
    "c_images": "Imagens",
    "c_title": "Titulo",
    "c_comment": "Comentário",
    "c_country": "País",
    "c_region": "Região",
    "c_district": "Distrito",
    "c_community": "Comunidade",
    "c_node": "Nó",
    "c_relation": "Relação",
    "c_from": "De",
    "c_subject": "Assunto",
    "c_to": "Para",
    "c_properties": "Propriedades",
    "c_question": "Questão",
    "c_questions": "Questões",
    "c_choices": "Opções",
    "c_include": "Incluir",
    "c_unique": "Único",
    "c_survey": "Questionário",
    "c_survey_tg": "Survey / Grupo de Tarefas",
    "c_date": "Data",
    "c_dateq": "Data da Questão",
    "c_none": "Nenhum",
    "c_period": "Período",
    "c_hour": "Hora",
    "c_day": "Dia",
    "c_week": "Semana",
    "c_month": "Mês",
    "c_year": "Ano",
    "c_matches": "matches",
    "c_filter": "Filtro",
    "c_inclusive": "Inclusivé",
    "c_value": "Valor",
    "c_clear": "Limpar",
    "c_options": "Opções",
    "c_data": "Informação",
    "c_layers": "Camadas",
    "c_settings": "Definições",
    "c_start": "Início",
    "c_end": "Fim",
    "c_step": "Passo",
    "c_back": "Anterior",
    "c_target": "Acção",
    "c_trigger": "Trigger",
    "c_content": "Conteudo",
    "c_today": "Hoje",
    "c_attach": "Anexar",
    "c_details": "Detalhes",
    "c_action": "Acção",
    "c_actions": "Ações",
    "c_mapid": "Id. do Mapa",
    "c_zoom": "Niveis do Zoom",
    "c_zoom_data": "Zoom aos dados",
    "c_vector_data": "Dados do vector",
    "c_vector_style": "Estilo do vector",
    "c_style": "Estilo",
    "c_portrait": "Vertical",
    "c_landscape": "Horizontal",
    "c_tools": "Ferramentas",
    "c_required": "Colocar como obrigatório",
    "c_not_required": "Colocar como opcional",
    "c_del_sel": "Eliminar seleccionados",
    "c_assign_sel": "Definir selecionado como atribuído",
    "c_print": "Imprimir",
    "c_repeat": "Repetir",
    "c_persist": "Persistir",
    "c_repeats": "Repetir",
    "c_scheduled": "Agendado",
    "c_t_c": "Termos e condições",
    "c_agree": "Eu concordo com o",
    "c_select": "Seleccionar",
    "c_status": "Estado",
    "c_coords": "Coordenadas",
    "c_task": "Tarefa",
    "c_rec": "(Recomendado)",
    "c_source": "Origem",
    "c_show": "Mostrar",
    "c_hide": "Esconder",
    "c_total": "Total",
    "c_totals": "Totais",
    "c_instances": "Instâncias",
    "c_device": "Dispositivo",
    "c_success": "Sucesso",
    "c_errors": "Erros",
    "c_error": "Erro",
    "c_warning": "Aviso",
    "c_lt": "Hora local",
    "c_standard": "Padrão",
    "c_simserial": "Número Serial SIM",
    "c_location": "Localização",
    "c_ident": "Identificador",
    "c_version": "Versão",
    "c_deleted": "Eliminado",
    "c_yes": "Sim",
    "c_no": "Não",
    "c_reason": "Razão",
    "c_complete": "Terminado",
    "c_record": "Registo",
    "c_records": "Registos",
    "c_of": "de",
    "c_media": "Media",
    "c_changes": "Alterações",
    "c_meta": "Meta Itens",
    "c_calc": "Cálculos",
    "c_trans": "Traduzir",
    "c_org": "Organização",
    "c_orgs": "Organizações",
    "c_ent": "Empreendimento",
    "c_all_s": "Todos os questionários",
    "c_all": "Todos",
    "c_event": "Evento",
    "c_note": "Nota",
    "c_server": "Servidor",
    "c_cols": "Colunas",
    "c_cols_packed": "Colunas Escolhidas",
    "c_add": "Adicionar",
    "c_create": "Criar",
    "c_generate": "Gerar",
    "c_imp_xls": "Importar Planilha",
    "c_format": "Formatar",
    "c_xlstype": "Formato Excel",
    "c_roles": "Perfis",
    "c_s_roles": "Perfis de Pesquisa",
    "c_role": "Perfil",
    "c_id": "ID",
    "c_insert": "Inserir",
    "c_tz": "Fuso Horário",
    "c_undef": "Não Definido",
    "c_license": "Número Licença",
    "c_in": "em",
    "c_notin": "não em",
    "c_rev": "Reverter",
    "c_for": "Para",
    "c_normal": "Normal",
    "c_heatmap": "Mapa de Calor",
    "c_auth": "Autorizado",
    "c_merge": "Mesclar",
    "c_append": "Acrescentar",
    "c_discard": "Descartar",
    "c_keys": "Chaves",
    "c_counts": "Contagens",
    "c_unsav": "Você tem alterações não salvas, tem certeza que quer sair?",
    "c_off": "Desligado",
    "c_on": "Ligado",
    "c_replace": "Substituir",
    "c_retry": "Tentar Novamente",
    "c_alink": "Link anônimo",
    "c_excel": "Excel",
    "c_csv": "CSV",
    "c_json": "JSON",
    "c_geojson": "GeoJSON",
    "c_osm": "Openstreetmap",
    "c_shape": "Shape",
    "c_kml": "KML / KMZ",
    "c_vrt": "VRT / CSV",
    "c_stata": "Stata / CSV",
    "c_spss": "SPSS / CSV",
    "c_pdf": "PDF",
    "c_phone": "Número de Telefone",
    "c_photo": "Fotografia",
    "c_rep_type": "Sub Form",
    "c_cl": "Copiar Link",
    "c_codl": "Copiar Link OData",
    "c_cb": "Copiar para Área de Transferência",
    "c_c": "Copiado",
    "c_quantity": "Quantidade",
    "c_after": "Depois",
    "c_units": "Unidades",
    "c_duration": "Duração",
    "c_msg": "Mensagem",
    "c_completed": "Completado",
    "c_unsubscribed": "Inscrição Cancelada",
    "c_unsubscribe": "Cancelar Inscrição",
    "c_subscribe": "Inscrever",
    "c_expired": "Expirado",
    "c_subscriberid": "Id Inscrito",
    "c_unsent": "Email não enviado",
    "c_pending": "Pendente",
    "c_ok": "OK",
    "c_move": "Mover",
    "c_parent_form": "Formulário Pai",
    "c_child_form": "Formulário Filho (Repete)",
    "c_other": "Outro",
    "c_random": "Randomizar",
    "c_annotate": "Anotar",
    "c_draw": "Desenhar",
    "c_field_list": "Lista de Campos",
    "c_table_list": "Lista de Tabelas",
    "c_recover": "Recuperar Arquivo Anterior",
    "c_lat": "Latitude",
    "c_lon": "Longitude",
    "c_browse": "Browse",
    "c_reject": "Rejeitar",
    "c_history": "Histórico",
    "c_events": "Events",
    "c_resend": "Reenviar",
    "c_late": "Atrasado",
    "c_custom": "Personalizado",
    "c_access": "Accesso",
    "c_person": "Pessoa",
    "c_people": "Pessoas",
    "c_contacts": "Contatos",
    "c_teams": "Equipes",
    "c_mailouts": "Mails enviados",
    "c_mailout": "Mail enviado",
    "c_campaigns": "Campanhas",
    "c_campaign": "Campanha",
    "c_manual": "Manual",
    "c_submitter": "Enviador",
    "c_code": "Código",
    "c_dirn": "Direção",
    "c_current": "Atual",
    "ft": "Tipo de ficheiro",
    "ft_xls": "Form. XLS",
    "ft_xls_orig": "Ficheiro Original",
    "ft_xml": "Form. XML",
    "ft_codebook": "Codebook",
    "ft_pdf": "Modelo PDF",
    "ft_spss": "Ficheiro SPS (SPSS)",
    "tm_s_del": "Mostrar form. eliminados",
    "tm_d_forms": "Eliminar formulários",
    "tm_r_forms": "Recuperar formulários",
    "tm_e_forms": "Apagar formulários",
    "tm_c_form": "Criar formulário",
    "tm_c_form_rep": "Substituir um Formulário",
    "tm_c_xls": "Usando o editor de folha de cálculo",
    "tm_g_temp": "Descarregar Modelo",
    "tm_g_new": "Criar novo formulário",
    "tm_g_open": "Abrir um Formulário",
    "tm_g_temp_i1": "Descarregue o modelo para criar um novo formulário no seu computador. Quando terminar, envie-o para o servidor usando o botão de envio de formulário em baixo. Terá de selecionar primeiro o ficheiro XLS que contém o formulário que criou e dar-lhe um nome.",
    "tm_g_temp_i3": "Guia de Referência",
    "tm_ul_f": "Enviar a folha de cálculo",
    "tm_si": "Indique o identificador do questionário",
    "tm_up": "Enviar Modelo",
    "tm_ups": "Enviar Formulário",
    "tm_add_for": "Adicionar reencaminhamento",
    "tm_ref_f": "Atualizar lista de Formulários",
    "tm_o_u": "Página Original para Upload",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccione um questionário",
    "a_exp_leg2": "Formato:",
    "a_exp_notes": "Exportar notas:",
    "a_exp_meta": "Incluir Meta Dados:",
    "a_exp_odata2": "Restringir tipos Odata para aqueles suportados pelo OData 2:",
    "a_exp_split": "lat / lon separadas:",
    "a_exp_merge": "Comprimir vários:",
    "a_sel_ways": "Selecione caminhos (se existirem):",
    "a_sel_forms": "Selecione formulários para incluir:",
    "a_sel_query": "Não há queries para exportar. Você vai precisar criar uma usando o menu Queries no módulo Dashboard",
    "a_sel_model": "Editar o modelo do questionário",
    "a_type": "Tipo de Gráfico",
    "a_showon": "Mostrar em",
    "a_ss": "Selecione questionário",
    "a_sq": "Selecione questão",
    "a_gb": "Agrupar por",
    "a_ts": "Séries de tempo",
    "a_sl": "Exibir Rótulo",
    "a_g_gps": "Coordenadas GPS na região",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Data de",
    "a_to_date": "Até data",
    "a_fq": "Questão a filtrar",
    "a_res": "Por favor, indique uma razão",
    "a_res_5": "Por favor forneça uma razão de pelo menos 5 caracteres",
    "a_mb": "Marcado como inválido",
    "a_oo": "fora de",
    "a_cm": "Membros do grupo",
    "a_dv": "Mostrar detalhes",
    "a_rd": "Relatório de Definições",
    "a_rp": "Relatório de Parâmetros",
    "a_embed": "Embutir imagens no Arquivo Excel",
    "a_hxl": "HXL",
    "a_query": "Selecione uma query",
    "a_fn": "Função",
    "a_ni": "Você precisa habilitar carregamento de tarefas para este formulário nas configurações de formulários na página do editor",
    "a_nx": "Novo XLSX",
    "a_lx": "XLSX Herdado",
    "a_lh": "XLSX / HTML Herdado",
    "a_ua": "Atividade do Usuário",
    "a_ul": "Localizações do Usuário",
    "a_tc": "Este Gráfico",
    "a_start_pk": "Primeira Chave Primária",
    "a_end_pk": "Última Chave Primária",
    "a_dd_sl": "Exibir os resultados",
    "a_dd_ocha_map": "Mostra a localização das resposta para %s1 na questão '%s2' na pesquisa '%s3'.",
    "a_dd_percent_map": "Mostra a porcentagem de respostas que selecionaram %s1 na questão  '%s2' na pesquisa '%s3'.",
    "a_dd_average_map": "Mostra a média de respostas para %s1 na questão '%s2' na pesquisa '%s3'.",
    "a_dd_count_map": "Mostra a contagem de respostas para %s1 na questão '%s2' na pesquisa '%s3'.",
    "a_dd_total_map": "Mostra o total de respostas para %s1 na questão '%s2' na pesquisa '%s3'.",
    "a_dd_none_map": "Mostra as respostas para %s1 na questão '%s2' na pesquisa '%s3'.",
    "a_dd_ocha_table": "Mostra a localização das respostas para para cada opção na questão '%s2' na pesquisa '%s3'.",
    "a_dd_percent_table": "Mostra a porcentagem das respostas que selecionaram cada opção na questão '%s2' na pesquisa '%s3'.",
    "a_dd_average_table": "Mostra a média das respostas para cada opção na questão '%s2' na pesquisa '%s3'.",
    "a_dd_count_table": "Mostra a contagem das respostas para cada opção na questão '%s2' na pesquisa '%s3'.",
    "a_dd_total_table": "Mostra o total das respostas para cada escolha na questão '%s2' na pesquisa '%s3'.",
    "a_dd_none_table": "Mostra as respostas para cada escolha na questão '%s2' na pesquisa '%s3'.",
    "a_filter": "Mostrando %s1 registros de %s2",
    "a_dd_units": "(unidades são %s1)",
    "a_dd_group": "Agrupado pelas respostas para a questão '%s1'.",
    "a_dd_group_interval": "Agrupado pelas respostas para a questão '%s1' and by '%s2'.",
    "a_dd_interval": "Agrupado por '%s1'",
    "a_dd_where": "<b>Onde %s1 é igual a %s2</b>",
    "_scheduled_start": "Início Agendado",
    "a_exp_media_msg": "Exportações com midia são limitados a %s1 registros.",
    "a_exp_msg": "Exportações sem midia são limitados a %s1 registros.",
    "a_exp_msg2": "Você está atualmente exportando %s2 registros. Defina o início e o fim dos registros para adequar a este limite.",
    "a_exp_start": "O registro de início precisa ser menor ou igual ao registro do final",
    "msg_pc": "O intervalo do lembrete deve ser maior que zero",
    "msg_pk_sel": "Você só pode selecionar o identificador de registro se tiver marcado a caixa de seleção \"Atualizar uma pergunta diferente\"",
    "msg_wait": "A aguardar uma resposta do servidor. Por favor, tente novamente dentro de alguns segundos",
    "msg_reason": "Por favor, indique uma razão:",
    "msg_sel_survey": "Tem de seleccionar um questionário",
    "msg_sel_dates": "A data de início é maior que a data do fim",
    "msg_no_from": "Se especificar data de término agendado, então deve especificar data de início agendada",
    "msg_sel_q": "Tem de seleccionar uma questão para mostrar no gráfico",
    "msg_val_prot": "Tem de especificar o protocolo (http:// ou https://) juntamente com o nome do servidor",
    "msg_val_p": "Tem de selecionar um projecto para este formulário",
    "msg_val_rf": "Tem de selecionar um form. remoto",
    "msg_val_rh": "Tem de selecionar um servidor remoto",
    "msg_val_u_id": "Tem de indicar o utilizador",
    "msg_val_pass": "Tem de indicar a palavra-chave",
    "msg_nv": "Por favor especifique um novo valor",
    "msg_val_nm": "Nome é requerido",
    "msg_val_dl_dist": "Se definido então a distância para download deve ser maior que 100 metros",
    "msg_val_show_dist": "Se definido então a distância para exibição deve ser maior que 10 metros",
    "msg_val_ad": "Se atribuindo uma tarefa usando dados coletados então você precisa especificar os dados",
    "msg_val_ad2": "A role adicional deve ser especificada somente se a primeira role foi especificada",
    "msg_val_file": "Um arquivo deve ser selecionado",
    "msg_val_let": "O nome tem de começar por uma letra ou underscore",
    "msg_pwd_l": "Senhas, se especificadas, devem ser maiores que 1 caractere",
    "msg_pwd_m": "Senhas não coincidem",
    "msg_add_notification": "Adicionar Notificação",
    "msg_edit_notification": "Alterar notificação",
    "msg_send_notification": "Enviar notificação",
    "msg_nn": "Sem Notificações",
    "msg_add_map": "Adicionar Mapa",
    "msg_edit_map": "Alterar Mapa",
    "msg_sel_form": "Selecione Formulário:",
    "msg_sel_media": "Seleccione a pergunta multimédia:",
    "msg_sel_media_f": "Selecioe Arquivo de Mídia",
    "msg_err_save": "Erro: A gravação falhou:",
    "msg_err_del": "Erro: A eliminação falhou:",
    "msg_err_cr": "Erro: Criar falhou:",
    "msg_err_upd": "Erro: Actualização falhou:",
    "msg_err_res": "Erro: A recuperação falhou:",
    "msg_err_block": "Erro: O bloqueio falhou:",
    "msg_err_get_f": "Erro: A leitura dos formulários falhou:",
    "msg_err_get_r": "Erro: Obter roles falhou:",
    "msg_err_get_a": "Erro: Obter alertas falhou:",
    "msg_err_get_q": "Erro: Obter questões falhou:",
    "msg_err_get_s": "Erro: Obter pesquisas falhou:",
    "msg_upd": "Update concluído",
    "msg_err_nc": "Nome não pode incluir uma vírgula",
    "msg_err_wait": "Expirou o tempo de espera do servidor ou não existem perguntas neste projecto para atribuir a um utilizador. Se o projecto tem perguntas, então tente novamente dentro de alguns segundos",
    "msg_err_cert": "O servidor remoto não contém um certificado válido, tente usar http:// em vez de https://",
    "msg_no_edit_rep": "Não pode alterar um registo que foi substituido por outro.",
    "msg_confirm_del": "Tem a certeza que deseja eliminar",
    "msg_confirm_del_one": "Apagar %s1 somente de %s2",
    "msg_confirm_del_all": "Apagar %s1 de todas as Organizações: %s2",
    "msg_confirm_tasks": "este grupo e todas as suas tarefas?",
    "msg_del_r": "Tem a certeza que deseja eliminar estas regiões?",
    "msg_erase": "Tem a certeza que deseja eliminar permanentemente estes questionários e todos os seus dados?",
    "msg_restore": "Tem a certeza que deseja recuperar estes questionários?",
    "msg_del_recs": "Existe(m) %s1 registo(s) introduzido(s) para %s2. Tem a certeza que deseja eliminar esta informação?",
    "msg_del_s": "Tem a certeza que deseja eliminar estes questionários?",
    "msg_del_data": "Tem a certeza que deseja eliminar todos os dados nestes questionários?",
    "msg_del_groups": "Esta pesquisa é parte de um grupo e apagar seus dados irá também apagar dados destas outras pesquisas",
    "msg_res_data": "Você tem certeza de que quer restaurar todos os dados deste survey para os envios originais?",
    "msg_del_data2": "Tem mesmo a certeza?",
    "msg_del_rep": "Tem a certeza que deseja eliminar este relatório?",
    "msg_del_users": "Tem a certeza que deseja eliminar estes utilizadores?",
    "msg_del_projects": "Tem certeza que quer realmente apagar este projeto?",
    "msg_del_roles": "Tem certeza que quer apagar essas roles?",
    "msg_del_orgs": "Tem a certeza que deseja eliminar estas organizações?",
    "msg_del_ents": "Tem certeza que quer realmente apagar estes empreendimentos?",
    "msg_del_q": "Tem a certeza que deseja eliminar esta questão?",
    "msg_del_cl": "Tem a certeza que deseja eliminar esta lista de opções?",
    "msg_del_c": "Tem a certeza que deseja eliminar esta opção?",
    "msg_rep_f": "Tem certeza que quer substituir esse filtro de escolhas?",
    "msg_del_not": "Tem certeza que quer apagar notificações",
    "msg_n_v": "Inválido",
    "msg_u_f": "Erro: envio falhou",
    "msg_u_nt": "Não foram encontradas nenhumas etiquetas NFC",
    "msg_csv": "Só são permitidos ficheiros CSV e ficheiros ZIP que contenham CSV",
    "msg_inv_email": "Não é um endereço de e-mail válido",
    "msg_dup_email": "Email duplicado. Algum outro usuário tem este email.",
    "msg_email_req": "Se quer enviar email para o usuário então endereço de email deve ser especificado.",
    "msg_email_dom": "Email de usuário não deve incluir o domínio. Então, para um endereço de email de example@org.com, o username seria 'example'",
    "msg_dup_ident": "Identidade de usuário duplicada. Por favor, altere a identidade de usuário.",
    "msg_cs": "Clique para filtrar ou alterar esta coluna",
    "msg_nrf": "Nenhum resultado encaminhado para outro servidor",
    "msg_saf": "Selecione um formulário para ver os usuários que baixaram este formulário",
    "msg_nf": "Sem formulários",
    "msg_ns": "Sem envios",
    "msg_us": "Origem Desconhecida",
    "msg_tg_ns": "Grupo de tarefas não selecionado",
    "msg_tg_rd": "A regra do grupo de tarefas foi apagada",
    "msg_no_roles": "Não há regras ativas. Então não há restrições de acesso.",
    "msg_has_roles": "Somente usuários que tiverem uma das seguintes roles ativas têem acesso permitido",
    "msg_one_f": "Ao menos um formulário precisa ser selecionado",
    "msg_one_f2": "Um formulário deve ser selecionado",
    "msg_embed": "O arquivo Excel deve ser xls ou xlsx para embutir imagens",
    "msg_pss": "Por favor selecione uma pesquisa",
    "msg_nm": "Nenhuma imagem, áudio ou vídeo encontrado",
    "msg_pr": "Senha foi resetada.",
    "msg_es": "Email foi enviado para",
    "msg_refresh": "Você fez algumas alterações e não salvou ainda, certeza que quer atualizar?",
    "msg_leave": "Você fez algumas alterações e não salvou ainda, certeza que quer sair?",
    "msg_test": "Você fez algumas alterações e vai precisar salvar antes de testar o formulário.",
    "msg_not_f": "não foi encontrado",
    "msg_ren": "renomeado para",
    "msg_nq": "Você não tem queries definidas, use o botão 'adicionar query' para adicionar uma",
    "msg_dup_f": "Este form já está na query",
    "msg_ui": "Espaços não são permitidos na identidade do usuário",
    "msg_sp": "Selecione um projeto para ver o status dos formulários",
    "msg_ab_ns": "Ou adicionar tarefas a partir de dados já enviados ou adicionar tarefas a partir de dados ainda a serem enviados ou ambas devem ser selecionadas",
    "msg_n1": "emails em uma questão",
    "msg_n2": "emails em meta item",
    "msg_sms_n1": "Enviar SMS para",
    "msg_sms_n2": "números inseridos em resposta a uma questão",
    "msg_ds_s": "Download iniciado. Se houverem muitos dados isto pode levar algum tempo, por favor seja paciente.",
    "msg_survey_replaced": "Pesquisa substituída",
    "msg_survey_loaded": "Pesquisa carregada",
    "msg_reg": "Registro aceito. Um email foi enviado para %s1 com um link que você pode usar para definir sua senha.",
    "msg_uns": "Cancelamento bem-sucedido",
    "msg_s1": "Um email foi enviado para o endereço que você forneceu. Clique no link para confirmar sua inscrição",
    "msg_s2": "Inscrito com sucesso",
    "msg_s3": "Digite seu endereço de email para se inscrever para emails",
    "msg_pd_key": "Especifique uma chave de dados",
    "msg_one_role": "Pelo menos uma role deve ser selecionada",
    "msg_dup_name": "Nome duplicado",
    "msg_prev_select": "Não há seleção de questões prévia de onde obter valores. Você pode querer definir um filtro personalizado",
    "msg_no_proj": "O usuário não tem projetos",
    "msg_pformat": "Parâmetros especificados no outro campo devem ser separados por ponto e vírgula e conter um sinal de igual. Por exemplo: a=x;b=y",
    "msg_filter_col": "Você especificou um filtro de Coluna de '%s1'; portanto, você precisa especificar um filtro para aplicar",
    "msg_numb_ts": "Separador de milhares não terá efeito, a menos que números também seja selecionado",
    "msg_warn_likert": "Likert funciona apenas em formulários da Web. Você também pode tentar perguntas do tipo \"intervalo\" que funcionam no aplicativo Android e nos Webforms.",
    "msg_warn_likert_n": "Likert funciona apenas com o tipo de seleção normal",
    "msg_choice_value": "O valor da escolha deve ser especificado",
    "msg_search_source": "Você deve selecionar pesquisa ou csv como fonte dos dados de escolha",
    "msg_search_source2": "O arquivo de origem ou pesquisa deve ser selecionado",
    "msg_pdfcols_count": "A largura total de todas as colunas deve adicionar até 10",
    "msg_pdfinv_zoom": "Zoom deve ser entre 1 e 20",
    "msg_pdfcols_width": "A largura da coluna deve estar entre 1 e 10 incluindo",
    "msg_pe": "O número de dias antes da expiração da senha deve ser um número inteiro maior que 0",
    "msg_restore_started": "A restauração dos dados da pesquisa foi iniciada. Pressione atualizar para ver o progresso. Esse processo pode levar alguns minutos se os arquivos a serem recuperados estiverem no armazenamento externo",
    "msg_persist": "Tarefas persistentes permanecem no dispositivo mesmo depois de concluídas. O usuário deve rejeitar a tarefa quando terminar com ela",
    "msg_no_uns_orgs": "Não há organizações em que esse endereço de e-mail seja cancelado",
    "msg_res_name": "%s1 é um nome reservado",
    "msg_trans_to": "O pedido de tradução expirou. No entanto, ele ainda deve estar funcionando em segundo plano e você pode visualizar os resultados atualizando a página",
    "e_b_e": "Baseado num questionário existente",
    "e_s_r": "Guardar resultados numa tabela partilhada",
    "t_complete": "Mostrar Tarefas Concluidas",
    "t_show": "Mostrar tarefas para:",
    "t_assign_type": "Tipo de atribuição",
    "t_assign": "Atribuir utilizador",
    "t_assign_roles": "Atribuir a usuários com função",
    "t_fixed_role": "E esta função",
    "t_add_group": "Adicionar grupo de tarefas",
    "t_del_group": "Eliminar grupo de tarefas",
    "t_edit_group": "Editar grupo de tarefas",
    "t_lt_file": "Carregar tarefas a partir de um ficheiro",
    "t_choose_user": "Escolha o utilizador a atribuir às tarefas seleccionadas",
    "t_ce": "Limpar tarefas existentes",
    "t_ce_warn": "Isto irá limpar todos os dados no questionário. Tem a certeza que deseja continuar?",
    "t_ceg": "Criar grupo de tarefas vazio",
    "t_cfe": "Criar a partir de dados existentes",
    "t_ep": "Projecto existente",
    "t_es": "Questionário existente",
    "t_ec": "Escolha Existente",
    "t_et": "Texto Existente",
    "t_nt": "Novo Texto",
    "t_ns": "Novo Questionário",
    "t_ft": "Filtrar tarefas",
    "t_aft": "Filtro Avançado",
    "t_df": "Filtro de Data",
    "t_fq": "Filtrar por pergunta",
    "t_so": "Opção seleccionada",
    "t_sn": "Indique valor numérico",
    "t_st": "Indique valor de texto",
    "t_ue": "Actualizar resultados actuais",
    "t_pp": "Preencher previamente o formulário com dados existentes",
    "t_nid": "Sem dados iniciais",
    "t_ap": "Parâmetros de morada",
    "t_nfc": "NFC / Localização",
    "t_assigned": "Atribuido",
    "t_fl": "Ficheiro enviado",
    "t_tl": "Modelo Carregado",
    "t_efnl": "Erro: o ficheiro não foi enviado",
    "t_ens": "Erro não salvo",
    "t_add_tasks": "Clique no mapa onde deseja adicionar novas tarefas. Quando terminar clique no botão \"Guardar Tarefas\"",
    "t_add_task": "Adicionar tarefa",
    "t_edit_task": "Editar tarefa",
    "t_add_tasks2": "Adicionar Tarefas",
    "t_save_tasks": "Guardar Tarefas",
    "t_tasks_only": "Só Tarefas",
    "t_tg": "Grupo de Tarefas",
    "t_tasks": "Tarefas",
    "t_id": "Informação inicial",
    "t_n_s": "Tarefas sem hora de inicio",
    "t_drag": "Arraste uma tarefa e largue no calendário",
    "t_g": "Orientação",
    "t_pol": "Completar Tudo",
    "t_auto": "Permitir que os usuários se designem (se não atribuídos)",
    "t_auto2": "Auto Atribuição",
    "t_ass_done": "Você concluiu esta atribuição?",
    "t_defn": "Definição de Grupo de Tarefas",
    "t_au": "Todos usuários",
    "t_u": "Não Atribuído",
    "t_ad": "Atribuir a partir de valores de dados",
    "t_af": "Criar tarefas a partir dos resultados enviados após a criação deste grupo de tarefas",
    "t_ac": "Criar tarefas a partir de resultados que já foram enviados",
    "t_start": "Define a hora de início e a duração da tarefa em relação a quando ela é criada ou uma data na pesquisa de origem",
    "t_all": "Todas as tarefas",
    "t_dl_dist": "Distância de download (metros)",
    "t_dl_dist_i": "O usuário precisará estar a essa distância do centro geográfico das tarefas deste grupo de tarefas antes de fazer o download no dispositivo",
    "t_show_dist": "Distância de exibição (metros)",
    "t_show_dist_i": "O usuário precisará estar a essa distância da tarefa antes que ela seja exibida no dispositivo",
    "t_show_console": "Mostrar no console",
    "new": "Não Atribuído",
    "accepted": "Atribuido",
    "submitted": "Terminado",
    "rejected": "Rejeitado",
    "cancelled": "Cancelado",
    "deleted": "Eliminado",
    "unsent": "Não Enviado",
    "unsubscribed": "Inscrição Cancelada",
    "e_u_err": "Erro ao enviar o formulário",
    "e_u_exists": "existe no projecto",
    "e_h_rename": "Mude o nome do formulário ou elimine o antigo",
    "e_u_sm_no_list": "questão do tipo \"select_multiple\" sem indicação do nome da lista de valores",
    "e_h_sm_no_list": "Verifique as definições do formulário. Confirme que indicou o nome da lista de valores para todas as questões do tipo \"select_multiple\"",
    "e_u_so_no_list": "questão do tipo \"select_one\" sem indicação do nome da lista de valores",
    "e_h_so_no_list": "Verifique as definições do formulário. Confirme que indicou o nome da lista de valores para todas as questões do tipo \"select_one\"",
    "e_unknown": "Erro desconhecido",
    "e_get_help": "Contacte o serviço de assistência técnica",
    "e_calc": "Erro ao calcular formulas",
    "e_h_calc1": "Verifique a coluna \"calculation\" por formulas inválidas (uma formula válida retorna o valor verdadeiro ou falso)",
    "e_h_calc2": "Ou então verifique a coluna \"relevant\" por uma formula que não retorne um valor verdadeiro ou falso",
    "e_inv_f": "Função inválida",
    "e_h_f1": "Confirme que todas as letras estão em minusculas",
    "e_h_f2": "Verifique que não existam erros ortográficos no nome da função",
    "e_val": "Erro de validação",
    "e_circ": "Procure por referências circulares",
    "e_in_q": "na questão",
    "e_h_c1": "Um 'filtro relevante ou de cálculo ou de escolha' para a pergunta está se referindo a si mesmo, em vez de se referir a outra pergunta",
    "e_h_c2": "Condições do tipo \"relevant\" são avaliadas antes da questão ser apresentada, pelo que não podem fazer referência à sua própria questão",
    "e_brackets": "Número impar de parentesis na função",
    "e_text": "Erro com o seguinte texto:",
    "r_o_n": "Nome da Organização",
    "r_y_n": "O seu nome",
    "r_y_e": "O seu e-mail",
    "r_y_o": "Website da Organização",
    "r_f": "Formulário de registo",
    "r_s": "Inscrições",
    "mon_l200": "(últimos 200)",
    "mon_gtb": "Agrupar totais por",
    "mon_nl": "Não foi carregado",
    "mon_ue": "Erros de Upload",
    "mon_dup": "Duplicados",
    "mon_att": "Anexos extra",
    "mon_sa": "Mostrar como",
    "mon_zoom_grid": "Zoom às grelhas",
    "mon_show_grid": "Mostrar grelhas",
    "mon_clear_grid": "Limpar grelhas",
    "mon_create_grid": "Criar grelha",
    "mon_del_grid": "Eliminar grelha",
    "mon_sel_layer": "Seleccione uma camada a adicionar ao mapa como sobreposição",
    "mon_c_reg": "Criar uma nova região",
    "mon_c_reg_i": "Indique um nome para a região e a largura de cada célula em metros. Clique no mapa para definir o centro de uma das células. Mantenha a tecla \"SHIFT\" pressionada e arraste o rato para definir os limites.",
    "mon_name_cond": "(minusculas, sem espaços ou números)",
    "mon_cw": "Largura da Célula (em metros, maior que 10)",
    "mon_centre": "Centro: (clique no mapa)",
    "mon_bounds": "Limite: (clique e arraste no mapa com a tecla \"SHIFT\" pressionada)",
    "mon_sel_del": "Seleccione as regiões que deseja eliminar",
    "mon_ud": "Data de envio",
    "mon_pi": "Id. Telefone",
    "mon_fr": "Razão da falha",
    "mon_file": "Ficheiro com resultados brutos",
    "mon_optin_msg": "Mensagens Opt in",
    "mon_send_count": "Enviar Contagem",
    "mon_pending_count": "Mensagens Pendentes",
    "error": "Erro",
    "success": "Sucesso",
    "an_auth": "Autor",
    "an_published": "Publicado",
    "an_publish": "Publicar",
    "an_dr": "Intervalo de datas",
    "an_csel": "Limpar selecção",
    "r_add": "Adicionar relatório",
    "r_ed": "Editar relatório",
    "r_del": "Apagar relatórios",
    "an_nd": "Não há dados disponíveis",
    "an_nmd": "Nenhum dado corresponde ao filtro",
    "an_mod_hint": "A página de modificação permite fazer alterações em massa no texto. Você pode selecionar um valor de texto específico e alterar todas as ocorrências para outro valor. Isso é muito útil para corrigir inconsistências ortográficas. Você também pode alterar os valores de texto em \"outras\" perguntas para uma das opções selecionadas. Você também pode atualizar o código de barras e calcular perguntas. Outros tipos de perguntas não são suportados, pois, por exemplo, não faria sentido fazer uma alteração em massa de uma idade inteira de 25 para 26, onde quer que ela ocorresse. Você pode revisar as modificações selecionando a página de revisão. <br/><br/>No entanto, você pode atualizar perguntas inteiras, decimais e seleção única, marcando a caixa de seleção \"Atualizar uma pergunta diferente\". Nesse caso, a alteração será aplicada a todas as perguntas que correspondem aos valores existentes das duas perguntas. Na maioria dos casos, você não precisará dessa opção.",
    "Upload Time": "Enviar",
    "_start": "Hora Inicial",
    "_end": "Hora Final",
    "percent": "Porcentagem",
    "count": "Contagem",
    "none": "Nenhum",
    "average": "Média",
    "max": "Máximo",
    "min": "Mínimo",
    "sum": "Soma",
    "changes": "Atualizar",
    "task": "Tarefa",
    "notification": "Notificação",
    "created": "Criado",
    "wf_sig": "Assinatura",
    "ed_map_zoom": "Zoom do Mapa",
    "ed_hidden": "Ocultar no aplicativo móvel",
    "ed_selfie": "Abrir câmera no modo selfie",
    "ed_new": "Exigir que uma nova foto seja tirada",
    "ed_read_nfc": "Ler uma tag NFC ao invés de um código de barras",
    "ed_gt_0": "deve ser maior que 0 ou não definido",
    "ed_add_to": "Anexar à pergunta",
    "ed_app": "Coloque um apêndice",
    "ed_barcode": "Mostrar como código de barras",
    "ed_hyperlink": "Mostrar um hyperlink para a imagem",
    "ed_col_width": "largura da coluna %s1",
    "ed_place_map": "Permite que o usuário selecione sua localização em um map",
    "ed_l_bold": "Tornar o marcador em negrito",
    "ed_caps": "Tornar o rótulo todo em maiúsculas",
    "ed_npb": "Nova Página Antes",
    "ed_sa": "Espaçamento acima",
    "ed_bgc": "Cor de Fundo do Rótulo",
    "ed_vbgc": "Valor da Cor de Fundo",
    "ed_mc": "Cor do Marcador",
    "ed_height": "Altura permitida para resposta",
    "ed_lw": "Largura do rótulo",
    "ed_pdfcols_help": "Pode haver no máximo 10 colunas. As larguras das colunas devem adicionar até 10.",
    "ed_pdf_layout": "Layout PDF",
    "ed_pdfno": "Ocultar pergunta na exportação de pdf",
    "ed_date_type": "Tipo de Data",
    "ed_select_type": "Selecione o Tipo",
    "ed_nc": "Sem Calendário",
    "ed_my": "Mês e Ano",
    "ed_bikram": "Nepali",
    "ed_coptic": "Cóptico",
    "ed_ethiopian": "Etíope",
    "ed_islamic": "Islâmico",
    "ed_myanmar": "Myanmar",
    "ed_persian": "Persa",
    "ed_r": "Avaliação",
    "ed_bear": "Orientação",
    "ed_sep": "Separador de Milhares",
    "ed_sn": "Mostrar teclado numérico",
    "ed_numb_cols": "Número de Colunas",
    "ed_min": "Mínimo",
    "ed_adv": "Avanço Automático",
    "ed_ac": "Auto Completar",
    "ed_compact": "Compacto",
    "ed_compact_adv": "Compacto com avanço automático",
    "ed_image_map": "Imagem de Mapa",
    "ed_pick": "Seletor",
    "ed_as": "Adicionar Busca",
    "ed_rf": "Formulário Referência",
    "ed_in": "Nome da Instância",
    "ed_io": "Ordem da Instância",
    "ed_ic": "Contagem da Instância",
    "ed_ep": "Projecto existente",
    "ed_es": "Questionário existente",
    "ed_qt": "Texto da questão",
    "ed_dn": "Nome de Exibição",
    "ed_ct": "Texto da opção",
    "ed_qh": "Sugestão da questão",
    "ed_cl": "Lista de Opções",
    "ed_appearance": "Aparência",
    "ed_parameters": "Parâmetros",
    "ed_con": "Limite",
    "ed_con_msg": "Mensagem do limite",
    "ed_sct": "Salvar alterações antes de executar tradução automática",
    "ed_rel": "Relevante",
    "ed_req": "Obrigatório",
    "ed_req_msg": "Mensagem obrigatória",
    "ed_nreq": "Não obrigatória",
    "ed_ap": "Reproduzir automáticamente",
    "ed_at": "Limiar de precisão do GPS",
    "ed_ls": "Questionário ligado",
    "ed_ro": "Somente Leitura",
    "ed_ls_add": "Adicionar ligação",
    "ed_l": "Ligado",
    "ed_nl": "Não ligado",
    "ed_r_msg": "Mensagem de texto obrigatório",
    "ed_o_o_g": "Apenas uma questão geométrica pode ser adicionada ao formulário",
    "ed_f_l": "O formulário a ser lançado deve ser especificado como um parâmetro",
    "ed_emp_rep": "Sub-formulários e grupos devem ter pelo menos uma pergunta visível. Perguntas tipo cálculo não são consideradas visíveis",
    "ed_hrk": "Chave Única",
    "ed_dk": "Chave de Dados",
    "ed_csv": "Ficheiro CSV",
    "ed_c_s": "Origem das Opções",
    "ed_cws": "Planilha de Opções",
    "ed_i_c": "Criado",
    "ed_st": "Tabela Compartilhada",
    "ed_ld": "Permitir carregar dados de ficheiro",
    "ed_pd": "Puxar dados de outra pesquisa",
    "ed_i_bo": "Baseado Em",
    "ed_i_tn": "Nomes de Tabela",
    "ed_tlf": "Formulário de Nível Superior",
    "ed_namedia": "Midia não pode ser usada nesta pergunta",
    "ed_ab": "Adicionar Antes",
    "ed_aa": "Adicionar Depois",
    "ed_aq": "Adicionar Nova Pergunta",
    "ed_ancl": "Adicionar Nova Lista de Opções",
    "ed_anc": "Adicionar Nova Opção",
    "ed_cs": "Seleção em Cascata\n ",
    "ed_cspq": "Pergunta Anterior de Seleção",
    "ed_csp": "Seleção Anterior",
    "ed_cf": "Filtro Customizado",
    "ed_afc": "Adicionar Filtro de Coluna",
    "ed_clabs": "Rótulo des Opções",
    "ed_clab": "Rótulo de Opção",
    "ed_cval": "Valor da Opção",
    "ed_fv": "Valor do Filtro",
    "ed_sfv": "Segundo Valor do Filtro",
    "ed_choice_f": "Filtro de Opção",
    "ed_vc": "Nomes das opções devem conter apenas letras, números. sublinhados, traços e pontos",
    "ed_vq": "O nome da pergunta deve começar com uma letra, sublinhado ou dois pontos e conter apenas letras, números, sublinhados, traços e pontos",
    "ed_gl": "Para uma pergunta de localização, o nome deve ser 'the_geom'",
    "ed_ogl": "Somente perguntas de local podem ter o nome 'the_geom'",
    "ed_ns": "Adicione uma nova pesquisa usando o menu 'Arquivo' antes de adicionar perguntas",
    "ed_kp": "Política Chave",
    "ed_s1": "Selecione Um",
    "ed_s": "Selecione Vários",
    "ed_image": "Imagem",
    "ed_image_type": "Tipo de Imagem",
    "ed_int": "Inteiro",
    "ed_gps": "Ponto GPS",
    "ed_calc": "Cálculo",
    "ed_s_calc": "Cálculo de Servidor",
    "ed_audio": "Áudio",
    "ed_video": "Vídeo",
    "ed_bc": "Código de Barras",
    "ed_dt": "Data e Hora",
    "ed_t": "Hora",
    "ed_dec": "Decimal",
    "ed_gps_line": "Linha GPS",
    "ed_gps_area": "Área GPS",
    "ed_ack": "Reconhecimento",
    "ed_range": "Intervalo",
    "ed_graph": "Gráfico",
    "ed_qs": "Conjunto de Perguntas",
    "ed_ee": "Não incluir respostas vazias nos relatórios",
    "ed_er": "Não é possível salvar até que os erros sejam corrigidos",
    "ed_blocked": "A pesquisa foi bloqueada. As alterações não podem ser salvas. Você pode desbloquear a pesquisa na página de gerenciamento de formulários.",
    "ed_cml": "Não é possível modificar os idiomas enquanto houver alterações não salvas.",
    "ed_cx": "Não é possível exportar para um xlsForm enquanto houver alterações não salvas",
    "ed_csr": "Não é possível exportar para um xlsForm enquanto houver alterações não salvas",
    "ed_fi": "Identificador de Formulário",
    "ed_dl": "Idioma Padrão",
    "ed_td": "Dados de Tempo",
    "ed_rl": "Gravar localização com perguntas",
    "ed_rc": "Auditoria de alterações nas perguntas",
    "ed_hod": "Ocultar o formulário nos dispositivos",
    "ed_s_g": "Grade (Formulários Web)",
    "ed_s_p": "Páginas",
    "ed_c_del_q": "Pergunta Apagada",
    "ed_c_del_o": "Opção %s1 excluída da lista de opções %s2",
    "ed_c_chg_p": "propriedade %s1 da pergunta %s2 foi alterada para: %s3 de: %s4",
    "ed_c_add_q": "Pergunta %s1 adicionada com o tipo %s2",
    "ed_c_add_o": "Opção %s1 foi adicionada à lista de opções: %s2",
    "ed_c_settings": "Configurações alteradas",
    "ed_mmf": "Gerenciar Ficheiros de Mídia Para este Formulário",
    "ed_sl": "Pesquisa a ser lançada",
    "ed_qk": "Pergunta para armazenar a chave retornada",
    "ed_qkc": "Pergunta no formulário lançado para obter essa chave de formulários",
    "ed_pl": "Layout da Página",
    "ed_w": "Largura na grade do formulário web",
    "ed_m": "Filtro",
    "ed_fc": "Coluna de Filtro",
    "ed_sfc": "Segunda Coluna de Filtro",
    "ed_addcalc": "Adicionar cálculo aqui",
    "contains": "contém",
    "startsWith": "começaCom",
    "endsWith": "terminaCom",
    "ed_ds": "Pesquisa de Dados",
    "ed_os": "Pesquisa de Supervisão",
    "ed_nb": "Sem Botões",
    "ed_offline": "Offline e Online",
    "ed_online": "Somente Online",
    "ed_csa": "alterações aplicadas com sucesso",
    "ed_csf": "alterações falharam",
    "ed_transd": "Traduções concluídas do idioma %s1 para o idioma %s2",
    "ed_ow": "Substituir traduções existentes",
    "mf_id": "Incluir apagadas",
    "mf_fd": "Dados do formulário",
    "mf_md": "Dados de gestão",
    "mf_sc": "Mostrar Controles",
    "mf_sc_i": "Escolha as colunas que deseja visíveis na tabela e clique no botão \"Aplicar\". Depois já pode ordenar por essas mesmas colunas",
    "mf_qr": "Colunas QR",
    "mf_bc_i": "Selecione as colunas que você quer ver como código de barras na tabela e nos relatórios",
    "mf_st": "Rastreamento de submissões",
    "mf_gr": "Obter relacionados",
    "mf_of": "Pesquisa de Supervisão",
    "mf_no": "Não há formulários de supervisão. Eles podem ser adicionados na guia \"Formulários de Supervisão Disponíveis\"",
    "mf_sel": "Selecione o formulário que você deseja gerenciar e o formulário de supervisão com o qual deseja gerenciar.",
    "mf_ao": "Formulários de Supervisão Disponíveis",
    "mf_mf": "Formulários gerenciados",
    "mf_ld": "Detalhes da Camada",
    "mf_tr": "Um título é obrigatório",
    "mf_sr": "Relatório Resumido",
    "mf_lock": "Travar para edição",
    "mf_rel": "Liberar",
    "mf_mr": "Meus registros",
    "mf_ur": "Registros não atribuídos",
    "mf_or": "Outros registros",
    "mf_max": "Máximo de registros",
    "mf_clear": "Limpar visualização de registro único",
    "mf_hc": "Ocultar Controles",
    "lo_back": "Anterior",
    "lo_out": "Não está autenticado no",
    "lo_lo": "Não está autenticado",
    "u_show_u": "Mostrar utilizadores com grupo de segurança",
    "u_show_p": "Mostrar utilizadores no projecto",
    "u_show_r": "Mostrar usuários com função",
    "u_show_o": "Mostrar usuários da organização",
    "u_add": "Adicionar utilizador",
    "u_del": "Eliminar utilizador",
    "u_mv": "Mover para Organização",
    "u_mv_ent": "Mover para Empresa",
    "u_add_p": "Adicionar Projecto",
    "u_del_p": "Eliminar Projecto",
    "u_add_o": "Adicionar Organização",
    "u_del_o": "Eliminar Organização",
    "u_add_e": "Adicionar Empresa",
    "u_del_e": "Apagar Empresa",
    "u_add_r": "Adicionar Função",
    "u_edit_r": "Editar Função",
    "u_del_r": "Apagar Função",
    "u_det": "Detalhes do utilizador",
    "u_ident": "Identificação (minúsculas e sem espaços ou endereço de e-mail)",
    "u_email": "Enviar e-mail ao novo utilizador",
    "u_set_p": "Especificar palavra-chave",
    "u_sg": "Grupos de segurança",
    "u_det_p": "Detalhes do Projecto",
    "u_det_ur": "Detalhes da Função do Usuário",
    "u_det_o": "Detalhes da Organização",
    "u_det_e": "Detalhes da Empresa",
    "u_det_o_rep": "Opções de publicação do Relatório",
    "u_det_o_ft": "Opções do Aplicativo Móvel",
    "u_det_o_wf": "Opções do Formulário Web",
    "u_det_pbc": "Cor de Fundo da Página",
    "u_det_paperbc": "Cor de Fundo do Papel",
    "u_det_fp": "Posição do rodapé (da direita em pixels)",
    "u_ft_del": "Eliminar registos submetidos do equipamento",
    "u_ft_prev_track_dis": "Impedir a desativação do rastreamento de local",
    "u_ft_img_size": "Máximo de pixels da borda longa de uma imagem",
    "u_ft_img_camera": "Tamanho original da câmera",
    "u_ft_vs": "Muito pequeno (640px)",
    "u_ft_s": "Pequeno (1024px)",
    "u_ft_m": "Médio (2048px)",
    "u_ft_l": "Grande (3072px)",
    "u_ft_ld": "Enviar dados da localização do utilizador",
    "u_ft_os": "Ativar os menus de estilo ODK para excluir, enviar, editar e obter novos formulários",
    "u_ft_am": "Ativar menu administrativo ODK",
    "u_ft_ex": "Desabilitar menu sair",
    "u_ft_in": "Permitir que o usuário defina o nome da instância",
    "u_ft_rv": "Permitir a abertura de formulários finalizados para revisão",
    "u_ft_as": "Sincronizar Automaticamente",
    "u_ft_ms": "Sincronização Manual",
    "u_ft_sw": "WIFI",
    "u_ft_sw_c": "WIFI e rede celular",
    "u_ft_sop": "Definir no Equipamento",
    "u_ft_tasks": "Número máximo de tarefas para download",
    "u_ft_back_nav": "Navegação para trás",
    "u_ft_nav": "Navegação na Tela",
    "u_ft_pw_timeout": "Número de dias antes do vencimento da senha",
    "u_ft_pw_policy": "Política de Senha",
    "u_ft_never": "Nunca exigir logon",
    "u_ft_always": "Sempre exigir logon no início do aplicativo",
    "u_ft_periodically": "Exigir logon periodicamente",
    "u_ft_swipes": "Usar swipes horizontais",
    "u_ft_buttons": "Usar botões avançar/retroceder",
    "u_ft_swipes_buttons": "Usar swipes e botões",
    "u_det_o_email": "Opções de e-mail",
    "u_det_o_other": "Outras opções",
    "u_det_o_limits": "Limites de Uso Mensal",
    "u_other_edit": "Permitir editar resultados",
    "u_email_tasks": "Permitir o envio de emails de tarefas",
    "u_use_api": "Permitir acesso à API",
    "u_submissions": "Permitir envios",
    "u_notifications": "Permitir notificações",
    "u_sms": "Permitir SMS",
    "u_mb_k": "Chave Mapbox",
    "u_mb_a": "Conta Mapbox",
    "u_mb_s": "Id de Estilo Mapbox",
    "u_g_k": "Chave Google Maps",
    "u_smtp": "Host SMTP",
    "u_e_dom": "Domínio de Email",
    "u_e_nm": "username de Email",
    "u_e_si": "Identificador do servidor",
    "u_e_p": "Senha do Email",
    "u_e_port": "Porta do Servidor de Email",
    "u_h_e": "Email para conseguir Ajuda",
    "u_rap": "Acesso Restrito",
    "u_rap_d": "Administradores poderão atribuir os usuários selecionados apenas a este projeto",
    "u_chg": "Alterado por",
    "u_usage": "Relatório de Uso",
    "u_notification": "Relatório de Notificação",
    "u_access": "Relatório de Acesso ao Formulário",
    "u_r_u": "Relatório de Uso de Recursos",
    "u_sms_url": "Url SMS",
    "u_sens_data": "Dados Sensíveis",
    "u_sens_ao": "Somente Administrador",
    "u_sens_sq": "Perguntas Assinatura",
    "u_sens_nr": "Sem restrições",
    "u_org_admin": "Administrador da Organização",
    "u_ent_admin": "Administrador da Empresa",
    "u_server_owner": "Proprietário do Servidor",
    "u_check_mv_p": "Tem certeza de que deseja mover os seguintes projetos (%s1) to %s2",
    "u_check_mv_o": "Tem certeza de que deseja mover a organização \"%s1\" para a empresa \"%s2\"",
    "u_only_one_ent": "Somente uma empresa foi criada. Você precisa criar outra para mover uma organização para lá",
    "u_co": "Organização Atual",
    "u_gr": "Obter Relatório",
    "u_sat": "Definir como Tema",
    "u_bl": "Logotipo do Banner do Formulário Web (altura 50px)",
    "u_ml": "Logo Principal",
    "u_nbc": "Barra de Navegação",
    "u_eoi": "Ativar Opt In",
    "admin": "Administrador",
    "analyst": "Analista",
    "enterprise admin": "Administrador da Empresa",
    "enum": "Enumerador",
    "manage": "Gerenciar Dados",
    "org admin": "Administrador Organizacional",
    "security": "Gerente de Segurança",
    "view data": "Ver Dados",
    "manage tasks": "Gerenciar Tarefas",
    "view own data": "Ver Próprios Dados",
    "u_clear_p": "Limpar saída vazia de projetos importados",
    "u_clear_u": "Limpar saída de usuários importados",
    "u_clear_r": "Limpar saída de funções importadas",
    "br_ci": "Não diferencia maiúsculas de minúsculas",
    "br_exact": "Combinação Exata",
    "br_cc": "Selecione as colunas que deseja testar para obter similaridades nos dados. Para cada coluna que você deseja testar, você pode selecionar uma função para ampliar o intervalo de valores que corresponderão.",
    "br_s": "Busca",
    "br_sdx": "Soundex",
    "br_cd": "Use a tabela de dados para esta visualização da pesquisa",
    "br_tf": "para perguntas de texto, incluindo select e select_one",
    "br_nf": "para perguntas numéricas, incluindo número inteiro e decimal",
    "sr_res": "Imagens Video Audio e ficheiros CSV",
    "sr_nfc": "Etiquetas NFC",
    "sr_uid": "UID NFC",
    "sr_geo": "Localizações Geográficas",
    "ar_af": "Adicionar ficheiros",
    "sr_g": "Grupo",
    "sr_fn": "Nome do ficheiro",
    "sr_m_ph": "Digite um nome para o seu mapa",
    "sr_m_d": "Digite uma descrição para este mapa (opcional)",
    "sr_m_mb": "Para o Mapbox, isso identifica o mapa, por exemplo: mapbox/light-v10",
    "sr_cr": "Relatórios Personalizados",
    "sr_al": "Usar Local Anônimo na Tarefa",
    "sr_ul": "Atualizar Local Existente",
    "sr_nl": "Salvar como Novo Local",
    "sr_sl": "Salvar Localização",
    "sr_si": "As coordenadas NFC UID e GPS que você especificar aqui podem ser salvas como um local nomeado ou usadas na tarefa como um local anônimo",
    "ar": "Árabe",
    "en": "Inglês",
    "fr": "Francês",
    "hi": "Hindi",
    "pt": "Português",
    "es": "Espanhol",
    "n_wf": "Formulário Web",
    "n_pdfp": "PDF (Retrato)",
    "n_pdfl": "PDF (Paisagem)",
    "n_eq": "Pergunta por Email",
    "n_ep": "Meta Item de Email",
    "n_smsq": "Pergunta SMS",
    "n_share": "Obter link",
    "n_cs_e": "Lista de endereços de email separados por vírgula",
    "n_ea": "Endereço de email",
    "n_eqc": "Pergunta que conterá os endereços de email a serem usados",
    "n_esc": "Assunto para o email (opcional)",
    "n_inc_ref": "Incluir pesquisas referenciadas",
    "n_lo": "Apenas dados de referência de formulários que foram lançados neste formulário",
    "task_reminder": "Lembrete de tarefas",
    "submission": "Submissão",
    "console_update": "Atualização do Console",
    "n_p": "Enviar lembrete depois",
    "n_oa": "Enviar email ao responsável original",
    "n_ap": "Adicionar marcador de posição",
    "n_si": "ID do Remetente do SMS",
    "n_sms_n_tt": "Lista de números de telefone separados por vírgula no formato +ccnnnnnnnnnn",
    "n_sms_q_tt": "Pergunta que conterá os números de SMS a serem usados",
    "n_e_p_tt": "Meta item ou pré-carregamento que conterá um endereço de e-mail para usar",
    "n_uq": "Atualizar Pergunta",
    "n_uv": "Atualizar Valor",
    "n_no_oversight": "Não há pesquisas de supervisão que possam ser usadas para atualizar os dados no console",
    "n_nv": "Um valor para a atualização deve ser especificado",
    "n_nq": "Uma pergunta de atualização deve ser especificada",
    "ro_fr": "Filtrar linhas",
    "ro_fc": "Colunas de filtro",
    "ro_fr_rule": "Linhas a serem mostradas",
    "ro_aq": "Perguntas Disponíveis",
    "ro_fr_i": "Digite uma regra que determine quais linhas serão mostradas para esta função. Coloque os nomes das perguntas em ${...}. Coloque o texto entre aspas simples. Verifique se há espaços entre os nomes das perguntas e os operadores, como = .<br/>Exemplo 1: ${region} = 'northern' <br/>Exemplo 2: ${age}> 16. Se nenhuma regra for especificada, todas as linhas serão mostradas.",
    "ro_fc_i": "Selecione as colunas para mostrar com este filtro. Se nenhuma coluna for selecionada, todas as colunas serão mostradas.",
    "ro_transform": "Transformação de dados longa para ampla",
    "i_m": "minutos",
    "i_h": "horas",
    "i_d": "dias",
    "i_sec": "segundo atrás",
    "i_secs": "segundos atrás",
    "i_min": "minuto atrás",
    "i_mins": "minutos atrás",
    "i_hour": "hora atrás",
    "i_hours": "horas atrás",
    "i_day": "dia atrás",
    "i_days": "dias atrás",
    "d_sound": "Reproduzir som em novo alerta",
    "d_rep_def_freq": "Relatório de Frequência",
    "bar_h": "Gráfico de Barras Horizontais",
    "bar_v": "Gráfico de Barras Verticais",
    "stacked": "Empilhados",
    "normalized": "Normalizado",
    "pie": "Gráfico de Pizza",
    "line": "Gráfico de Linha",
    "wordcloud": "Nuvem de Palavras",
    "length": "Contagem",
    "d_qtr": "25%",
    "d_half": "50%",
    "d_3qtr": "75%",
    "d_full": "100%",
    "d_sec": "Segundos",
    "d_min": "Minutos",
    "d_hour": "Horas",
    "d_day": "Dias",
    "d_c_day": "Contagem por dia",
    "d_c_month": "Contagem por mês",
    "d_c_year": "Contagem por ano",
    "d_add": "Adicionar",
    "d_add_c": "Adicionar Gráfico",
    "d_add_q": "Adicionar Nova Consulta",
    "d_add_f": "Adicionar Novo Formulário",
    "d_from_f": "Link do Formulário",
    "d_from_q": "Link da Pergunta",
    "d_edit_web": "Editar no Formulário Web",
    "d_d_pdf": "Download PDF",
    "d_layers": "Camadas do Mapa",
    "rev_upd_diff": "Atualize uma pergunta diferente para a pergunta de origem",
    "rev_sel_pk": "Selecione os dados a serem alterados usando uma chave primária",
    "rev_q_upd": "Pergunta a atualizar",
    "rev_text": "Texto",
    "rev_upd": "Atualizar",
    "rev_upd_t": "Atualizar pergunta de destino",
    "rev_upd_text": "Atualizar texto das perguntas",
    "rev_rt": "Substituir texto",
    "rev_rc": "registros com opção",
    "rev_fq": "da pergunta",
    "rev_rw": "registros com",
    "rev_rdm": "Revisar Modificações de Dados",
    "rev_ci": "Alterar ID",
    "rev_rb": "Revertido por",
    "rev_cb": "Alterado por",
    "rev_rcn": "Reverter Alteração Número",
    "rev_det": "Detalhes para Alteração Número",
    "rev_cq": "Pergunta Alterada",
    "rev_sc": "Opção Selecionada",
    "rev_usc": "Opção Não Selecionada",
    "ch_ds": "Dados do Gráfico",
    "quantity": "Quantidade",
    "free": "Grátis",
    "unitCost": "Custo Unitário",
    "amount": "Montante\n \n ",
    "server": "Servidor",
    "submissions": "Envios",
    "submissions_i": "Um limite de zero é ilimitado",
    "disk": "Disco",
    "rekognition": "Reconhecimento AWS",
    "rekognition_i": "Imagens",
    "translate": "Tradução AWS",
    "translate_i": "letras",
    "transcribe": "Transcrição AWS",
    "transcribe_i": "segundos de áudio",
    "static_map": "Mapa Estático Mapbox",
    "monthly": "Mensalidade",
    "org_bill_rpt": "Relatório de Uso da Organização",
    "bill_enable": "Ativar Faturamento",
    "bill_from": "Aplica-se a partir de",
    "bill_chg_date": "Data de Alteração",
    "bill_norates": "Nenhuma taxa foi definida para este %s1. Se o faturamento estiver ativado, as taxas para o %s2 serão usadas",
    "billing_disabled_msg": "O faturamento foi desativado",
    "rep_usage_project": "Uso por projeto",
    "rep_usage_survey": "Uso por pesquisa",
    "rep_usage_device": "Uso por dispositivo",
    "rep_values_question": "Pergunta de Valores",
    "rep_values": "Valores",
    "rep_wide_columns": "Colunas Largas",
    "rep_msg_min_keys": "Você deve especificar pelo menos uma pergunta-chave se a transformação estiver ativada",
    "rep_msg_v_q": "Você deve especificar uma pergunta de valores se a transformação estiver ativada",
    "rep_msg_min_values": "Você deve especificar pelo menos um valor se a transformação estiver ativada",
    "rep_msg_min_wc": "Você deve especificar pelo menos uma coluna larga se a transformação estiver ativada",
    "co_dd": "Detalhamento",
    "co_up": "Acima",
    "mo_ce": "Limpar Emails Não Enviados Existentes",
    "mo_ns": "Correio não selecionado",
    "mo_na": "Não Autorizado",
    "mo_nf": "O formulário da pesquisa não foi encontrado",
    "mo_ss": "Este formulário de pesquisa foi enviado com sucesso",
    "mo_exp": "Este formulário de pesquisa expirou",
    "mo_del_done": "Este formulário de pesquisa foi excluído",
    "mo_se": "Erro no Sistema",
    "mo_del": "em certeza de que deseja excluir a mensagem \"%s1\". Os destinatários que já tiveram e-mails enviados ainda poderão responder.",
    "mo_blocked": "Este formulário de pesquisa foi bloqueado. Tente novamente mais tarde ou entre em contato com o administrador para desbloquear",
    "mo_import": "Importar Emails",
    "mo_export": "Exportar Emails",
    "mo_subject": "Assunto do Email",
    "mo_content": "Conteúdo do Email",
    "mo_sent": "Enviado",
    "mo_sd": "Detalhes do Status",
    "mo_send": "Tem certeza de que está pronto para enviar os e-mails?",
    "svc_at": "Auto Traduzir",
    "svc_from_l": "Do Idioma",
    "svc_to_l": "Para o Idioma"
});