define(
{
    "m_home": "Inicio",
    "m_admin": "Administración",
    "m_tm": "Formularios",
    "m_analysis": "Análisis",
    "m_report": "Reporte",
    "m_reports": "Reportes",
    "m_reports_def": "Reportes predeterminados",
    "m_reports_org": "Reportes de Organización",
    "m_reports_leg": "Reportes Formato Anterior",
    "m_reports_new": "Nuevo Reportes",
    "m_reports_public": "Reportes Públicos",
    "m_refresh": "Actualizar",
    "m_email_unsent": "Enviar Correos",
    "m_email_gen": "Generar enlaces",
    "m_export": "Exportar",
    "m_export_media": "Exportar con Imágenes",
    "m_backup": "Descargar Backup",
    "m_backup_media": "Descargar Backup con Imágenes",
    "m_discuss": "Discusión",
    "m_modify": "Modificar",
    "m_web_forms": "Form. Web",
    "m_docs": "Documentación",
    "m_monitor": "Monitoreo",
    "m_user": "Usuarios",
    "m_assign": "Tareas",
    "m_query": "Consultas",
    "m_help": "Ayuda",
    "m_train": "Entrenamiento",
    "m_forgot_password": "Olvidé Contraseña",
    "m_register": "Contáctenos",
    "m_locations": "Rastreo",
    "m_section": "Sección",
    "m_notify": "Notificaciones",
    "m_view": "Ver",
    "m_attach": "Cargar adjuntos",
    "m_modules": "Modulos",
    "m_lr": "Reportes locales",
    "m_open": "Abrir",
    "m_new": "Nuevo",
    "m_import": "Importar",
    "m_calculations": "Cálculos",
    "m_resources": "Recursos Compartidos",
    "m_review": "Revisión",
    "m_mf": "Formularios de Supervisión",
    "m_br": "Ver Datos",
    "m_manage": "Supervisión",
    "m_dash": "Tablero de Datos",
    "m_console": "Consola",
    "m_s_m_f": "Configurar Form. de Supervisión",
    "m_task_m": "Gestión de Tareas",
    "m_user_profile": "Perfil de Usuario",
    "m_login": "Ingresar",
    "m_logs": "Registro de eventos",
    "m_info": "Información",
    "m_os": "Supervisión",
    "m_billing": "Facturación",
    "m_rates": "Tarifas",
    "m_billing_server": "Facturación por Servidor",
    "m_billing_orgs": "Facturación por Organización",
    "m_bill_level": "Nivel de Consumo",
    "ss_welcome": "Bienvenido al Servidor Versión:",
    "ss_welcome2": "Cambios en la versión",
    "ss_ft": "Obtener App Móvil",
    "ss_su": "Obtener el Cargador Smap",
    "c_alert": "Alerta",
    "c_alerts": "Alertas",
    "c_apply": "Aplicar",
    "c_api": "API",
    "c_api_builder": "Constructor API",
    "c_audit": "Auditoría",
    "c_auto": "Automática",
    "c_before": "Antes",
    "c_bundle": "Paquete",
    "c_cases": "Casos",
    "c_closed": "Cerrado",
    "c_cm": "Gestión de casos",
    "c_crit": "Criticidad",
    "c_default": "Por Defecto",
    "c_desc": "Descripción",
    "c_fingerprint": "Huella dactilar",
    "c_form": "Formulario",
    "c_forms": "Formularios Activos",
    "c_forward": "Reenviar",
    "c_link": "Enlace",
    "c_links": "Enlaces",
    "c_moved": "Movido",
    "c_opened": "Abierto",
    "c_periodic": "Periódico",
    "c_project": "Proyecto",
    "c_sub_form": "Subformulario (Repetición)",
    "c_threshold": "Umbral",
    "c_url": "URL",
    "c_webhook": "Web Hook",
    "c_forwarded": "Reenviados a otro servidor",
    "c_name": "Nombre",
    "c_company_name": "Empresa",
    "c_company_addr": "Dirección Comercial",
    "c_company_phone": "Teléfono Corporativo",
    "c_company_email": "Email Corporativo",
    "c_type": "Tipo",
    "c_file": "Archivo",
    "c_host": "Servidor",
    "c_rank": "Ordenar",
    "c_report": "Reporte",
    "c_user": "Usuario",
    "c_self": "El Mismo ",
    "c_sunday": "Domingo",
    "c_monday": "Lunes",
    "c_tuesday": "Martes",
    "c_wednesday": "Miércoles",
    "c_thursday": "Jueves",
    "c_friday": "Viernes",
    "c_saturday": "Sábado",
    "c_vertical": "Vertical",
    "c_projects": "Proyectos",
    "c_email": "Email",
    "c_escalate": "Escalar",
    "c_emails": "Emails",
    "c_sms": "SMS",
    "c_document": "Document",
    "c_twitter": "Twitter",
    "c_lang": "Idioma",
    "c_langs": "Idiomas",
    "c_pulldata": "Pulldata",
    "c_pulldata_r": "Pulldata en Repeticiones",
    "c_orientation": "Orientación",
    "c_password": "Contraseña",
    "c_c_p": "Confirmar Contraseña",
    "c_n_p": "Nueva contreña",
    "c_c_d": "Confirmar Eliminar",
    "c_r_p": "Cambiar Contraseña",
    "c_change_p": "Cambiar Contraseña",
    "c_reset": "Restablecer",
    "c_en": "Activar",
    "c_dis": "Desactivar",
    "c_loc_f": "Form. Local:",
    "c_rem_f": "Form. Remoto",
    "c_rem_u": "Usuario Remoto",
    "c_enabled": "Activado",
    "c_edit": "Editar",
    "c_del": "Eliminar",
    "c_undel": "Recuperar",
    "c_del_data": "Borrar Datos",
    "c_res_data": "Restaurar Datos",
    "c_archive_data": "Archivar Datos",
    "c_download": "Descargar",
    "c_upload": "Subir",
    "c_done": "Realizado",
    "c_cancel": "Cancelar",
    "c_save": "Guardar",
    "c_saved": "Guardado",
    "c_submit": "Enviar",
    "c_submitted": "Datos Enviados",
    "c_test": "Verificar",
    "c_validate": "Validar",
    "c_close": "Cerrar",
    "c_likert": "Likert",
    "c_logout": "Cerrar Sesión",
    "c_block": "Desactivar",
    "c_blocked": "Desactivada",
    "c_graph": "Gráfica",
    "c_map": "Mapa",
    "c_chart": "Gráfico",
    "c_charts": "Gráficos",
    "c_maps": "Mapas",
    "c_map_layers": "Cambiar Mapa",
    "c_table": "Tabla",
    "c_tables": "Tablas",
    "c_images": "Imágenes",
    "c_title": "Titulo",
    "c_comment": "Comentario",
    "c_country": "País",
    "c_region": "Región",
    "c_district": "Departamento",
    "c_community": "Ciudad",
    "c_node": "Nodo",
    "c_relation": "Relación",
    "c_from": "De",
    "c_subject": "Asunto",
    "c_to": "A",
    "c_properties": "Propiedades",
    "c_question": "Pregunta",
    "c_questions": "Preguntas",
    "c_choices": "Opciones",
    "c_include": "Incluir",
    "c_unique": "Unico",
    "c_survey": "Formulario",
    "c_survey_tg": "Formulario / Grupo de Tareas / Reporte",
    "c_date": "Fecha",
    "c_dateq": "Pregunta con Fecha",
    "c_none": "Ninguno",
    "c_period": "Período",
    "c_hour": "Hora",
    "c_day": "Día",
    "c_week": "Semana",
    "c_month": "Mes",
    "c_year": "Año",
    "c_daily": "Diaria",
    "c_weekly": "Semanal",
    "c_monthly": "Mensual",
    "c_yearly": "Anual",
    "c_matches": "Concidencia exacta",
    "c_filter": "Filtrar",
    "c_inclusive": "Inclusive",
    "c_value": "Valor",
    "c_clear": "Limpiar",
    "c_options": "Opciones",
    "c_data": "Datos",
    "c_layers": "Capas",
    "c_settings": "Ajustes",
    "c_start": "Inicia",
    "c_end": "Termina",
    "c_step": "Salto",
    "c_back": "Atras",
    "c_target": "Destino",
    "c_trigger": "Disparador",
    "c_content": "Mensaje",
    "c_today": "Hoy",
    "c_attach": "Adjunto",
    "c_details": "Detalles",
    "c_action": "Acción",
    "c_actions": "Acciones",
    "c_mapid": "Id. del Mapa",
    "c_zoom": "Niveles de Zoom",
    "c_zoom_data": "Zoom a Datos",
    "c_vector_data": "Datos del Vector",
    "c_vector_style": "Estilo del Vector",
    "c_style": "Estilo Web",
    "c_portrait": "Vertical",
    "c_landscape": "Horizontal",
    "c_tools": "Herramientas",
    "c_required": "Establecer todas como Obligatorias",
    "c_not_required": "Establecer todas como Opcionales",
    "c_del_sel": "Eliminar Seleccionada",
    "c_assign_sel": "Establecer seleccionado como asignada",
    "c_print": "Imprimir",
    "c_repeat": "Repetición",
    "c_persist": "Contínua",
    "c_repeats": "Repeticiones",
    "c_scheduled": "Programada",
    "c_t_c": "Términos y condiciones",
    "c_agree": "Estoy de acuerdo con",
    "c_select": "Seleccionar",
    "c_status": "Estatus",
    "c_coords": "Coordenadas",
    "c_task": "Tarea",
    "c_rec": "(Recomendado)",
    "c_source": "Fuente",
    "c_show": "Mostrar",
    "c_hide": "Ocultar",
    "c_total": "Total",
    "c_totals": "Totales",
    "c_instances": "Registros",
    "c_device": "Dispositivo",
    "c_success": "Realizado",
    "c_errors": "Errores",
    "c_error": "Error",
    "c_warning": "Advertencia",
    "c_lt": "Hora Local",
    "c_standard": "Estándar",
    "c_simserial": "Número de SIM Card",
    "c_location": "Ubicación",
    "c_ident": "ID",
    "c_version": "Version",
    "c_deleted": "Eliminada",
    "c_yes": "Si",
    "c_no": "No",
    "c_reason": "Motivo",
    "c_complete": "Completo",
    "c_record": "Registro",
    "c_records": "Registros",
    "c_of": "de",
    "c_media": "Multimedia",
    "c_resource": "Multimedia / CSV",
    "c_changes": "Cambios",
    "c_templates": "Plantillas PDF",
    "c_template": "Plantilla PDF",
    "c_meta": "Metadatos",
    "c_calc": "Cálculos",
    "c_trans": "Traducir",
    "c_org": "Organización",
    "c_orgs": "Organizaciones",
    "c_ent": "Empresa",
    "c_all_s": "Todos",
    "c_all": "Todos",
    "c_event": "Evento",
    "c_note": "Nota",
    "c_server": "Servidor",
    "c_cols": "Columnas",
    "c_cols_packed": "Columnas Empaquetadas",
    "c_add": "Adicionar",
    "c_create": "Crear",
    "c_generate": "Generar",
    "c_imp_xls": "Importar Formulario XLS (Excel)",
    "c_format": "Formato",
    "c_xlstype": "Formato Excel",
    "c_roles": "Roles",
    "c_s_roles": "Roles en Formularios",
    "c_role": "Rol",
    "c_id": "Id",
    "c_pivot": "Pivote",
    "c_insert": "Insertar",
    "c_tz": "Zona Horaria",
    "c_undef": "Sin Definir",
    "c_license": "Numero de Licencia",
    "c_in": "En (pertenece a)",
    "c_notin": "No pertenece",
    "c_rev": "Reverso",
    "c_for": "Para",
    "c_normal": "Normal",
    "c_heatmap": "Mapa de Calor",
    "c_auth": "Autorizado",
    "c_merge": "Combinar",
    "c_append": "Anexar",
    "c_discard": "Descartar",
    "c_keys": "Llaves",
    "c_counts": "Conteos",
    "c_unsav": "Tiene cambios no guardados. Esta seguro que quiere salir?",
    "c_off": "Desactivado",
    "c_on": "Activado",
    "c_rule": "Regla",
    "c_replace": "Reemplazar",
    "c_retry": "Reintentar",
    "c_alink": "Link Anónimo",
    "c_excel": "Excel",
    "c_word": "Word",
    "c_csv": "CSV",
    "c_json": "JSON",
    "c_geojson": "GeoJSON",
    "c_osm": "Openstreetmap",
    "c_shape": "Shape",
    "c_kml": "KML / KMZ",
    "c_vrt": "VRT / CSV",
    "c_stata": "Stata / CSV",
    "c_spss": "SPSS / CSV",
    "c_pdf": "PDF",
    "c_phone": "Teléfono",
    "c_photo": "Fotografía",
    "c_rep_type": "Repetición",
    "c_cl": "Copiar Hipervínculo",
    "c_codl": "Copiar enlace OData",
    "c_cb": "Copiar a Portapapeles",
    "c_c": "Copiado",
    "c_quantity": "Cantidad",
    "c_after": "Después",
    "c_units": "Unidades",
    "c_duration": "Duración",
    "c_msg": "Mensaje",
    "c_completed": "Realizada",
    "c_unsubscribed": "Email desactivado",
    "c_unsubscribe": "Desactivar email",
    "c_subscribe": "Suscribirse",
    "c_expired": "Expirado",
    "c_subscriberid": "Id. de suscriptor",
    "c_unsent": "Email no enviado",
    "c_pending": "Pendiente",
    "c_ok": "OK",
    "c_move": "Mover",
    "c_parent_form": "Formulario Padre",
    "c_child_form": "Formulario Hijo",
    "c_other": "Otros",
    "c_random": "Mostrar lista en orden aleatorio",
    "c_annotate": "Anotación",
    "c_draw": "Boceto",
    "c_field_list": "Preguntas en la misma pantalla",
    "c_table_list": "Estilo Cuadricula",
    "c_recover": "Traer plantilla PDF anterior",
    "c_lat": "Latitud",
    "c_lon": "Longitud",
    "c_browse": "Buscar",
    "c_reject": "Rechazar",
    "c_history": "Historial",
    "c_events": "Eventos",
    "c_resend": "Reenviar",
    "c_late": "Demorada",
    "c_custom": "Personalizado",
    "c_access": "Acceso",
    "c_person": "Persona",
    "c_people": "Suscripciones",
    "c_contacts": "Contactos",
    "c_teams": "Equipos",
    "c_mailouts": "Campañas",
    "c_mailout": "Campaña",
    "c_campaigns": "Campañas",
    "c_campaign": "Campaña",
    "c_manual": "Manual",
    "c_submitter": "Remitente",
    "c_code": "Código",
    "c_dirn": "Dirección",
    "c_rtl": "RTL",
    "c_current": "Actual",
    "c_quality": "Calidad",
    "c_low": "Baja",
    "c_external": "Externo",
    "c_preview": "Vista previa",
    "c_size": "Tamaño",
    "c_meters": "Metros",
    "c_accuracy": "Precisión",
    "ft": "Tipo de Archivo",
    "ft_xls": "Archivo XLS Form",
    "ft_xls_orig": "Archivo original",
    "ft_xml": "Formato XML",
    "ft_codebook": "Especificaciones del Formulario",
    "ft_pdf": "Plantilla del reporte PDF",
    "ft_spss": "Archivo SPS (SPSS)",
    "tm_s_del": "Mostrar formularios eliminados",
    "tm_s_block": "Mostrar formularios desactivados",
    "tm_d_forms": "Eliminar Formularios",
    "tm_r_forms": "Recuperar Formularios",
    "tm_e_forms": "Borrar Formularios",
    "tm_c_form": "Crear Un Formulario",
    "tm_c_form_rep": "Reemplazar un formulario",
    "tm_c_sr_rep": "Reemplazar un archivo de recurso compartido",
    "tm_c_xls": "Usando un formulario XLS (Excel)",
    "tm_g_temp": "Descargar Plantilla",
    "tm_g_new": "Nuevo Formulario",
    "tm_g_open": "Abrir un Formulario",
    "tm_g_temp_i1": "Descarga una plantilla para crear un nuevo formulario. Cuando haya terminado, podrá subirlo al servidor haciendo click en el botón de abajo, seleccionando el archivo XLS que contiene el formulario y asignarle el nombre correspondiente",
    "tm_g_temp_i3": "Guía de Referencia",
    "tm_ul_f": "Cargar Formulario XLS (Excel)",
    "tm_ul_sr": "Cargar un archivo de recurso compartido",
    "tm_ul_sl": "Cargue el archivo de ubicaciones compartidas",
    "tm_si": "Especifique el Identificador del formulario",
    "tm_up": "Subir Plantilla",
    "tm_add": "Agregar Plantilla",
    "tm_ups": "Cargar Formulario",
    "tm_add_for": "Agregar Adelante",
    "tm_ref_f": "Actualizar Lista de Formularios",
    "tm_o_u": "Ir a Versión Anterior",
    "tm_gw": "Solo se debe especificar un paquete para los formularios que comparten tablas. Si tiene dudas,  seleccione ninguna.",
    "a_ref_rate": "Intervalo de actualización automática en Análisis",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccione un formulario",
    "a_locn": "Seleccionar una pregunta de ubicación",
    "a_exp_leg2": "Formato de Salida:",
    "a_exp_notes": "Exportar Notas:",
    "a_exp_meta": "Incluir Meta Datos:",
    "a_exp_odata2": "Restringir tipo Odata a sólo aquellos soportados por Odata 2:",
    "a_exp_split": "Separar Coordenadas:",
    "a_exp_merge": "Comprimir Selecciones Múltiples:",
    "a_sel_ways": "Seleccionar modos (si tiene):",
    "a_sel_forms": "Seleccionar las tablas a incluir:",
    "a_sel_query": "No hay consultas para exportar. Deberá crear uno usando el menú de consultas en el módulo del tablero",
    "a_sel_model": "Editar Modelo de Formulario",
    "a_type": "Tipo de Gráfico",
    "a_showon": "Mostrar sobre",
    "a_ss": "Seleccionar Formulario",
    "a_sq": "Seleccionar pregunta",
    "a_gb": "Agrupar por",
    "a_ts": "Series de Tiempo",
    "a_sl": "Mostrar etiqueta",
    "a_g_gps": "Coordenadas GPS dentro de región",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Desde Fecha",
    "a_to_date": "Hasta Fecha",
    "a_fq": "Filtrar pregunta",
    "a_res": "Por favor suministre un motivo",
    "a_res_5": "Debe suministrar una razón de mínimo 5 caracteres",
    "a_mb": "Marcado Erróneo",
    "a_oo": "de",
    "a_cm": "Miembros de Cluster",
    "a_dv": "Mostrar Detalles",
    "a_rd": "Definición de Reporte",
    "a_rp": "Parámetros del Reporte",
    "a_lcr": "Lanzar Reporte Personalizado",
    "a_embed": "Colocar las imágenes incrustadas en Excel",
    "a_hxl": "HXL",
    "a_query": "Seleccione una consulta",
    "a_fn": "Función",
    "a_ni": "Se requiere habilitar \"Permitir Importar Datos\" para este formulario desde Ajustes  en el editor de formularios.",
    "a_nx": "XLSX Nuevo",
    "a_lx": "XLS Anterior",
    "a_lh": "XLS Anterior / HTML",
    "a_ua": "Actividad del Usuario",
    "a_ul": "Ubicaciones de usuarios",
    "a_tc": "Este Gráfico",
    "a_start_pk": "Llave Primaria (Record) Inicial",
    "a_end_pk": "Llave Primaria (Record) Final",
    "a_inc_ro": "Incluir preguntas de sólo lectura",
    "a_dd_sl": "Muestra los resultados",
    "a_dd_ocha_map": "Muestra la ubicación de las respuestas a %s1 en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_percent_map": "Muestra el porcentaje de respuestas seleccionadas  %s1 en la pregunta '%s2' de formulario '%s3'.",
    "a_dd_average_map": "Muestra el porcentaje de respuestas a %s1 en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_count_map": "Muestra el conteo de respuestas a %s1 en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_total_map": "Muestra el total de respuestas a %s1 en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_none_map": "Muestra las respuestas a %s1 en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_ocha_table": "Muestra la ubicación de las respuestas a cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_percent_table": "Muestra el porcentaje de respuestas que seleccionaron de cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_average_table": "Muestra el promedio de respuestas de cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_count_table": "Muestra el conteo de respuestas de cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_total_table": "Muestra el total de respuestas de cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_dd_none_table": "Muestra las respuestas de cada opción en la pregunta '%s2' del formulario '%s3'.",
    "a_filter": "Mostrando %s1 registros de %s2",
    "a_dd_units": "(unidades son %s1)",
    "a_dd_group": "Agrupado por las respuestas a la pregunta '%s1'.",
    "a_dd_group_interval": "Agrupado por las respuestas a la pregunta '%s1' y por '%s2'.",
    "a_dd_interval": "Agrupado por '%s1'",
    "a_dd_where": "<b>Donde %s1 es igual a %s2</b>",
    "_scheduled_start": "Inicio Programado",
    "a_exp_media_msg": "Descargar Backup con Imágenes tiene un límite de máximo %s1 registros.",
    "a_exp_msg": "Descargar Backup tiene un límte de máximo %s1 registros.",
    "a_exp_msg2": "Actualmente está intentando descargar %s2 registros. Establezca registro inicial y final de acuerdo a este límite.",
    "a_exp_start": "El registro inicial debe ser menor o igual al registro final",
    "msg_ipt": "Título de panel inválido",
    "msg_pdft": "Las plantillas PDF ahora se administran en la página de plantillas a la que se puede acceder desde el menú de herramientas",
    "msg_oet": "Solo se puede especificar el correo electrónico como destino cuando se selecciona periódico como disparador",
    "msg_mms": "Se debe especificar el mes",
    "msg_dms": "Se debe especificar el dia del mes",
    "msg_pc": "El intervalo de recordación debe ser mayor que cero.",
    "msg_pk_sel": "Sólo puede seleccionar el registro si ha marcado \"Actualizar una pregunta diferente\"",
    "msg_wait": "Esperando respuesta del servidor. Por favor intente de nuevo en unos segurndos",
    "msg_reason": "Por favor suministre un motivo:",
    "msg_rs": "Los recordatorios de tareas deben estar asociadas con un grupo de tareas que tenga tareas generadas a partir de datos existentes. No  se pueden enviar recordatorios para tareas simples.",
    "msg_sel_survey": "Se debe seleccionar un formulario",
    "msg_sel_dates": "Fecha Inicial es mayor que Fecha Final",
    "msg_no_from": "Se debe especificar fecha inicial, ya que se ha especificado fecha final.",
    "msg_sel_q": "Se debe seleccionar una pregunta para mostrar en la grafica",
    "msg_val_prot": "Se debe especificar un protocolo (http:// or https://) con el nombre del servidor",
    "msg_val_p": "Se debe seleccionar un proyecto para este formulario",
    "msg_val_rf": "Se debe seleccionar un formulario remoto",
    "msg_val_rh": "Debe seleccionar un servidor remoto",
    "msg_val_u_id": "Debe especificar un Id de usuario",
    "msg_val_pass": "Debe especificar una contraseña",
    "msg_nv": "Por favor especifique un nuevo valor",
    "msg_val_nm": "Se requiere un nombre",
    "msg_val_inv_nm": "El nombre no puede incluir un caracter / o un . . Especifique el nombre sin extensión.",
    "msg_val_gen_nm": "El nombre no puede contener corchetes angulares <>",
    "msg_val_period": "Se debe especificar un período mayor que 0",
    "msg_val_dl_dist": "Si se configura, la distancia de descarga debe ser superior a 100 metros.",
    "msg_val_show_dist": "Si se configura, la distancia para visualización debe ser superior a 10 metros.",
    "msg_val_ad": "Si asigna una tarea utilizando los datos recopilados, debe especificar los datos",
    "msg_val_ad2": "El rol adicional debería ser especificado sólamente si el primer rol fué especificado",
    "msg_val_file": "Se debe seleccionar un archivo",
    "msg_val_let": "El nombre debe empezar con una letra o guion al piso",
    "msg_pwd_l": "Contraseñas, si son especificadas, deben contener mínimo 1 caracter.",
    "msg_pwd_m": "Constraseñas no coinciden",
    "msg_add_notification": "Agregar Notificación",
    "msg_edit_notification": "Editar Notificación",
    "msg_send_notification": "Enviar Notificación",
    "msg_nn": "Sin Notificaciones",
    "msg_noi": "No hay mensajes de suscripción",
    "msg_add_map": "Agregar Mapa",
    "msg_edit_map": "Editar Mapa",
    "msg_sel_form": "Seleccione Tabla:",
    "msg_sel_media": "Seleccionar Pregunta Multimedia",
    "msg_mfn": "Generar nombres de archivo usando pregunta:",
    "msg_sel_media_f": "Seleccionar Archivo Multimedia",
    "msg_err_save": "Error: NO se pudo Guardar:",
    "msg_err_del": "Error:  NO se pudo Eliminar:",
    "msg_err_cr": "Error: En Creación",
    "msg_err_upd": "Error en cargue:",
    "msg_err_res": "Error: NO se pudo Restaurar:",
    "msg_err_block": "Error: NO se pudo Inhabilitar:",
    "msg_err_get_f": "Error: Fallo en carga de formularios:",
    "msg_err_get_r": "Error: Fallo en lectura de roles",
    "msg_err_get_a": "Error: Fallo en recibo de Alertas",
    "msg_err_get_q": "Error: Fallo en cargue de preguntas",
    "msg_err_get_s": "Error: Error trayendo formularios",
    "msg_err_get_c": "Error: no se pudo obtener la configuración de gestión de casos",
    "msg_err_bll": "Etiqueta en blanco para el idioma",
    "msg_upd": "Actualización Exitosa",
    "msg_err_nc": "Nombre no puede incluir una coma",
    "msg_err_wait": "Esperando conexión con servidor  o no hay formularios en este proyecto para asignar a un usuario. Si el proyecto tiene respuestas reintente en pocos segundos.",
    "msg_err_cert": "El servidor remoto no tiene una firma digital válida. Intente usar http:// en vez de https://",
    "msg_no_edit_rep": "No se puede editar un registro que ha sido reemplazado por otro registro",
    "msg_confirm_del": "Esta seguro que quiere eliminar",
    "msg_confirm_del_one": "Eliminar %s1  sólamente de %s2",
    "msg_confirm_del_all": "Eliminar %s1 de todas las organizaciones: %s2",
    "msg_confirm_tasks": "este grupo y todas sus tareas?",
    "msg_del_r": "Esta seguro de eliminar estas regiones?",
    "msg_erase": "Esta seguro de eliminar de manera permanente estos formularios y todo los datos asociados?",
    "msg_restore": "Esta seguro de restaurar estos formularios borrados?",
    "msg_del_recs": "Hay %s1 registros de datos del formulario %s2. Está seguro de eliminar estos datos?",
    "msg_del_s": "Está seguro de eliminar estos formularios?",
    "msg_del_data": "Está seguro de eliminar todos los datos en este formulario?",
    "msg_del_groups": "Este formulario es parte de un grupo y si borra sus datos, también se borrarán los datos de los otros formularios relacionados.",
    "msg_res_data": "Esta seguro de querer restaurar todos los datos de este formulario a los datos enviados originales?",
    "msg_del_data2": "Está seguro?",
    "msg_del_rep": "Está seguro de eliminar este reporte?",
    "msg_del_users": "Está seguro de eliminar estos usuarios?",
    "msg_del_projects": "Esta seguro de querer borrar este proyecto?",
    "msg_del_roles": "Esta seguro de eliminar estos roles?",
    "msg_del_cms": "¿Está seguro de que desea eliminar esta configuración?",
    "msg_del_orgs": "Está seguro de eliminar estas organizaciones?",
    "msg_del_ents": "Esta seguro de borrar estas empresas?",
    "msg_del_q": "Está seguro de eliminar esta pregunta?",
    "msg_del_cl": "Está seguro de eliminar esta lista de selección?",
    "msg_del_c": "Está seguro de borrar esta opción de selección?",
    "msg_rep_f": "Esta seguro de reemplazar el filtro de selección",
    "msg_del_not": "Está seguro de eliminar esta notificación?",
    "msg_n_v": "Inválido",
    "msg_u_f": "Error de fallo en subida de archivo",
    "msg_u_nt": "No se encontraron tags NFC",
    "msg_csv": "Sólo archivos CSV y ZIP conteniendo archivos CSV o multimedia son permitidos",
    "msg_inv_email": "No es un e-mail válido",
    "msg_dup_email": "Email duplicado. Otro usuario tiene este correo electrónico",
    "msg_email_req": "Si esta enviando un email al usuario entonces debe especificarse",
    "msg_email_dom": "Nombre de usuario de Email no debe incluir el dominio. Asi para una direccion como ejemplo.org, el nombre de usuario debería ser 'ejemplo'",
    "msg_dup_ident": "Usuario duplicado. Favor cambiar el usuario",
    "msg_cs": "Toque para filtrar u ordenar en esta columna",
    "msg_nrf": "No hay resultados direccionados a otro servidor",
    "msg_saf": "Seleccionar un formulario y ver que usuarios lo han descargado",
    "msg_nf": "No hay formularios",
    "msg_ns": "No hay enviados",
    "msg_us": "Fuente Desconocida",
    "msg_tg_ns": "No se ha seleccionado un Grupo de Tareas",
    "msg_tg_rd": "La regla del grupo de tareas se ha borrado",
    "msg_no_roles": "No hay roles habilitados. Por ende no hay restricciones en acceso.",
    "msg_has_roles": "Sólo los usuarios que tengan uno de los siguientes roles habilitados pueden tener acceso.",
    "msg_one_f": "Se debe seleccionar mínimo un formulario",
    "msg_one_f2": "Se debe seleccionar un formulario",
    "msg_embed": "El tipo excel debe ser xls o xlsx para incluir imágenes en las celdas",
    "msg_pss": "Por favor seleccione un formulario",
    "msg_nm": "No se encontraron archivos multimedia",
    "msg_pr": "Se ha restablecido la contraseña",
    "msg_pex": "Su contraseña ha caducado, establezca una nueva",
    "msg_es": "Se ha enviado email a",
    "msg_refresh": "Se han realizado algunos cambios y éstos no se han guardado aún, está seguro de actualizar sin guardar?",
    "msg_leave": "Se han realizado algunos cambios y éstos no se han guardado aún, está seguro de salir sin guardar?",
    "msg_test": "Se deben realizar algunos cambios y deben guardarse antes de realizar pruebas con el formulario",
    "msg_not_f": "no fué encontrado",
    "msg_ren": "renombrado a",
    "msg_nq": "No se tienen consultas definidas, use el botón \"Agregar Consulta\" para adicionar una",
    "msg_dup_f": "Este formulario ya está en la consulta",
    "msg_ui": "No se permiten espacios en el usuario",
    "msg_sp": "Seleccionar un proyecto para ver el estatus de los formularios",
    "msg_ab_ns": "Se debe seleccionar agregar tareas desde datos ya enviados o agregar tareas de datos a ser enviados o ambos.",
    "msg_n1": "emails en una pregunta",
    "msg_n2": "emails en metadato",
    "msg_sms_n1": "Enviar SMS a",
    "msg_sms_n2": "números ingresados en respuesta a una pregunta",
    "msg_ds_s": "Descarga iniciada. Si son muchos reportes, tomará algún tiempo..",
    "msg_ds_s_r": "Se inició la generación de reportes. Encontrará el reporte generado en el módulo de Reportes",
    "msg_survey_replaced": "Formulario reemplazado",
    "msg_survey_loaded": "Formulario cargado",
    "msg_reg": "Registro aceptado. Un email ha sido enviado a %s1 con el enlace para establecer su contraseña",
    "msg_uns": "El email se ha desactivado satisfactoriamente y no recibirá más notificaciones desde kontrolid",
    "msg_s1": "Un email se ha enviado a la dirección de correo electrónico suministrada. Haga click en el enlace para confirmar su suscripción.",
    "msg_s2": "El email fué activado exitosamente",
    "msg_s3": "Ingrese su email para suscribirse y recibir notificaciones",
    "msg_pd_key": "Especifique llave de datos",
    "msg_one_role": "Debe seleccionar al menos un rol",
    "msg_dup_name": "Nombre duplicado",
    "msg_prev_select": "No hay preguntas de selección previas de donde escoger valores. Puede usar un filtro personalizado",
    "msg_no_proj": "El usuario no tiene proyectos",
    "msg_pformat": "Los parámetros especificados en el campo \"Otros\" deben estar separados por punto y coma y contener un signo igual. Por ejemplo: a=x;b=y",
    "msg_filter_col": "Se ha especificado un filtro de columna '%s1', luego se necesita especificar un filtro para aplicarlo",
    "msg_filter_expr": "Se debe especificar una expresión para un tipo de búsqueda 'eval'",
    "msg_numb_ts": "Separador de miles sólo aplica si números se ha seleccionado ",
    "msg_warn_likert_n": "Likert sólo funciona con tipo de selección normal",
    "msg_choice_value": "Se debe especificar el valor de selección ",
    "msg_search_source": "Se debe seleccionar un formulario o un archivo csv como fuente de datos de selección",
    "msg_search_source2": "Se debe seleccionar un archivo fuente o un formulario",
    "msg_pdfcols_count": "El total de ancho de todas las columnas debe sumar hasta 10",
    "msg_pdfinv_zoom": "Zoom debe estar entre 1 y 20",
    "msg_pdfinv_round": "El redondeo de decimales puede estar entre 0 y 10",
    "msg_pdfcols_width": "Un ancho de columna debe estar entre 1 y 10 inclusive",
    "msg_pe": "El número de días antes que la contraseña expire debe ser un entero mayor que 0",
    "msg_restore_started": "El proceso de restauración de datos ha empezado. Para ver el progreso debe actualizar la página. Este proceso puede tomar varios minutos si los archivos a recuperar están en almacenamiento backup.",
    "msg_persist": "Las Tareas Contínuas permanecen en el dispositivo aun después de haberse realizado. El usuario debería rechazar la tarea cuando la haya terminado y ya no requiera su visualización.",
    "msg_no_uns_orgs": "El email no está activado en ninguna organización.",
    "msg_res_name": "%s1 es un nombre reservado",
    "msg_trans_to": "La solicitud de traducción ha alcanzado el límite. Sin embargo debería estar trabajando en segundo plano y se verán los resultados al refrescar la página",
    "msg_subs_bg": "Si ha cancelado su suscripción para recibir notificaciones por correo electrónico, puede volver a suscribirse para volver a recibirlas mediante esta página. La decisión de enviar notificaciones a una dirección de correo electrónico la toma un administrador, por lo que, aunque puede cancelar la suscripción a estas y luego volver a suscribirse en esta página, no puede solicitar notificaciones por correo electrónico cuando no se le envía ninguna.",
    "msg_fgt_p": "Ingrese la dirección de correo electrónico asociada a su cuenta. Se enviará un enlace a esa dirección que le permitirá restablecer su contraseña.",
    "msg_archive": "Se archivarán %s1 registros antes de %s2 inclusive de los siguientes formularios: %s3. ¿Desea continuar?",
    "msg_archive_done": "Archivado completo",
    "msg_archive_none": "No hay datos para archivar",
    "msg_archive_data": "¿Estás seguro de que quieres archivar los registros antiguos?",
    "msg_archive_before": "Se debe especificar la fecha antes de la cual se archivarán los registros.",
    "e_b_e": "Crear desde un formulario existente",
    "e_s_r": "Almacenar datos en tabla compartida  con datos origen",
    "t_complete": "Mostrar Tareas Realizadas",
    "t_show": "Mostrar tareas por:",
    "t_assign_type": "Tipo de Asignación",
    "t_assign": "Asignar a Usuario",
    "t_assign_roles": "Asignar a usuarios con rol",
    "t_fixed_role": "Y este rol",
    "t_add_group": "Adicionar Grupo de Tareas",
    "t_del_group": "Eliminar Grupo de Tareas",
    "t_edit_group": "Editar Grupo de Tareas",
    "t_lt_file": "Cargar Tareas desde Archivo",
    "t_choose_user": "Escoja el usuario para asignar la tarea seleccionada",
    "t_ce": "Borrar Datos Existentes",
    "t_ce_warn": "Esto borrará todos los datos existentes del formulario. Seguro que quiere hacer esto?",
    "t_ceg": "Crear Grupo de Tareas Vacio",
    "t_cfe": "Crear desde datos existentes",
    "t_ep": "Proyecto Existente",
    "t_es": "Formulario Existente",
    "t_ec": "Selección Existente",
    "t_et": "Texto Existente",
    "t_nt": "Nuevo Texto",
    "t_ns": "Nuevo Formulario",
    "t_ft": "Filtro de Tareas",
    "t_aft": "Filtro Avanzado",
    "t_df": "Filtro de Fechas",
    "t_fq": "Filtrar por Pregunta",
    "t_so": "Opción Seleccionada",
    "t_sn": "Establecer Valor Numérico",
    "t_st": "Establecer Valor de Texto",
    "t_ue": "Actualizar Resultados Existentes",
    "t_pp": "Rellene previamente el formulario con los datos existentes.",
    "t_nid": "Sin datos iniciales",
    "t_ap": "Datos adicionales (Texto en Línea 3 de Tareas)",
    "t_nfc": "NFC / Ubicación",
    "t_assigned": "Asignada",
    "t_eas": "Enviar correo electrónico al usuario asignado",
    "t_assignments": "Tareas",
    "t_iewe": "Se pueden enviar correos electrónicos para notificar a las personas cuando hay escalamiento",
    "t_fl": "Archivo cargado",
    "t_tl": "Plantilla Cargada",
    "t_efnl": "Error archivo no cargado",
    "t_ens": "Error No Guardado",
    "t_add_tasks": "Haga click en el mapa donde se quiera adicionar tareas. Cuando termine haga click en botón 'Guardar Tareas'",
    "t_add_task": "Agregar Tarea",
    "t_edit_task": "Editar Tarea",
    "t_add_tasks2": "Agregar Tareas",
    "t_save_tasks": "Guardar Tareas",
    "t_tasks_only": "Mostrar sólo las tareas (No formularios)",
    "t_tg": "Grupo de Tareas",
    "t_tasks": "Tareas",
    "t_id": "Datos Iniciales",
    "t_n_s": "Tareas sin fecha de inicio",
    "t_drag": "Arrastre una tarea y agréguela al calendario",
    "t_g": "Guía",
    "t_pol": "Realizar todos",
    "t_auto": "Permitir a los usuarios asignarse a sí mismos (si no están asignados)",
    "t_auto2": "Autoasignada",
    "t_ass_done": "Ha terminado esta asignación?",
    "t_defn": "Definición de Grupo de Tareas",
    "t_au": "Todos los usuarios",
    "t_u": "Sin asignar",
    "t_ad": "Asignar desde valores de datos",
    "t_af": "Crear tareas de resultados enviados después de crear el grupo de tareas",
    "t_ac": "Crear tareas de resultados que ya han sido enviados",
    "t_start": "Ajuste el tiempo de inicio y duración de la tarea relativos a cuando fue creado o a una pregunta de fecha",
    "t_all": "Todas las tareas",
    "t_dl_dist": "Distancia de descarga (metros)",
    "t_dl_dist_i": "El usuario deberá estar dentro de esta distancia del centro geográfico de las tareas en este Grupo de Tareas antes de que se descargue en su dispositivo",
    "t_show_dist": "Distancia para Visualización (metros)",
    "t_show_dist_i": "El usuario deberá estar dentro de esta distancia de la tarea antes de que sea visualizada en su dispositivo",
    "t_show_console": "Mostrar en consola",
    "new": "Sin asignar",
    "accepted": "Asignada",
    "submitted": "Realizada",
    "rejected": "Rechazada",
    "cancelled": "Cancelada",
    "deleted": "Eliminado",
    "restored": "Restaurado",
    "unsent": "No enviado",
    "unsubscribed": "Email desactivado",
    "e_u_err": "Error en cargue de formulario",
    "e_u_exists": "existe en proyecto",
    "e_h_rename": "Cambie el nombre del formulario o elimine el formulario anterior",
    "e_u_sm_no_list": "pregunta tipo selección múltiple (select_multiple) sin lista de nombres",
    "e_h_sm_no_list": "Revise el archivo .xls del formulario. Compruebe que haya una lista de nombres para todas las preguntas de selección múltiple (select_multiple)",
    "e_u_so_no_list": "pregunta tipo selección única (select_multiple) sin lista de nombres",
    "e_h_so_no_list": "Revise el archivo .xls del formulario. Compruebe que exista una lista de nombres para todas las preguntas de selección única (select_one)",
    "e_unknown": "Error desconocido",
    "e_get_help": "Contacte la mesa de ayuda:  contacto@kontrolid.com",
    "e_calc": "Error en cálculo",
    "e_h_calc1": "Revise la columna 'calculation' si hay una formula inválida (Una formula válida da como resultado verdadero (true) o falso (false))",
    "e_h_calc2": "Si no revise la columna 'relevant' si alguna formula no da como resultado true o false",
    "e_inv_f": "Función inválida",
    "e_h_f1": "Revise si hay letras mayúsculas. Todas las letras deben estar en minúsculas",
    "e_h_f2": "Revise errores de escritura en el nombre de la función",
    "e_val": "Error de Validación",
    "e_circ": "Revise por referencias circulares",
    "e_in_q": "en pregunta",
    "e_h_c1": "Una relevancia, o cálculo o filtro de selección se esta refiriendo a si mismo, en vez de referirse a otra pregunta.",
    "e_h_c2": "Declaraciones relevantes se están evaluando antes de una pregunta que si es ejecutada no podrá referirse a sus propias preguntas.",
    "e_brackets": "Falta cerrar corchetes en una función",
    "e_text": "Error en el siguiente texto:",
    "r_o_n": "Organización",
    "r_y_n": "Nombre",
    "r_y_e": "Email",
    "r_y_o": "Sitio web",
    "r_f": "Formulario de Registro",
    "r_s": "Subscripcion de email",
    "mon_l200": "(últimos 200)",
    "mon_gtb": "Agrupar Totales por",
    "mon_nl": "No cargado",
    "mon_ue": "Errores en Subida",
    "mon_dup": "Duplicados",
    "mon_att": "Con Adjuntos Extra",
    "mon_sa": "Mostrar como",
    "mon_zoom_grid": "Zoom a Cuadrículas",
    "mon_show_grid": "Mostrar Cuadrículas",
    "mon_clear_grid": "Limpiar Cuadrículas",
    "mon_create_grid": "Crear Cuadrículas",
    "mon_del_grid": "Eliminar Cuadrículas",
    "mon_sel_layer": "Seleccionar un capa adicional para mostrar sobre mapa.",
    "mon_c_reg": "Crear una nueva región",
    "mon_c_reg_i": "Ingrese un nombre para la región y el ancho de las celdas en metros. Haga click en el mapa para fijar el centro de las celdas. Presione la tecla mayúsculas) y arrastre el ratón para fijar los límites.",
    "mon_name_cond": "(minúsculas, sin espacios o números)",
    "mon_cw": "Ancho de Celda (in Metros. mayor que 10)",
    "mon_centre": "Centrar: (Haga clic en mapa)",
    "mon_bounds": "Límites: (haga clic y arrastre en el mapa mientras presiona la tecla de mayúsculas",
    "mon_sel_del": "Seleccione las regiones que quiere eliminar",
    "mon_ud": "Fecha de Subida",
    "mon_pi": "ID del Dispositivo",
    "mon_fr": "Causa del Fallo:",
    "mon_file": "Archivo de datos",
    "mon_optin_msg": "Opt in",
    "mon_send_count": "Enviar Conteo",
    "mon_pending_count": "Mensajes Pendientes",
    "mon_ignore_old": "Ignorar problemas que tengan más de 100 días",
    "error": "Error",
    "success": "Realizado",
    "mon_retry": "Volver a aplicar cargas fallidas",
    "mon_page": "Página %s1 de %s2 a %s3",
    "mon_uid": "Id de subida",
    "an_auth": "Autor",
    "an_published": "Publicado",
    "an_publish": "Publicar",
    "an_dr": "Rango de Fechas",
    "an_csel": "Limpiar Selección",
    "r_add": "Agregar Reporte",
    "r_ed": "Editar Reporte",
    "r_del": "Eliminar Reportes",
    "an_nd": "No hay datos disponibles",
    "an_nmd": "No hay datos resultantes con este filtro",
    "an_mod_hint": "Esta página permite hacer cambios masivos en textos. Se puede seleccionar un valor de texto específico y los cambios se producirán en todas las ocurrencias al otro valor. Este es útil para hacer ajustes de errores de escritura. También se pueden cambiar valores de preguntas de selección cuando se han incluidos cajones de texto para \"Otro\". También es posible actualizar valores de códigos de barras o cálculos. Tipos de preguntas que no son soportadas son por ejemplo enteros. Se pueden revisar las modificaciones realizadas  seleccionando la página Revisión<br/><br/>  Se puede sin embargo, actualizar enteros, decimales y preguntas de selección marcando el botón de chequeo \"Actualizar una pregunta diferente a la pregunta original: \". En este caso los cambios aplicarán a todas las preguntas que conincidan con los valores existentes de las dos preguntas. En la mayoría de los casos no será necesario esta opción.",
    "Upload Time": "Hora de Subida",
    "_start": "Hora Inicio",
    "_end": "Hora Final",
    "percent": "Porcentaje",
    "count": "Conteo",
    "none": "Ninguno",
    "average": "Promedio",
    "max": "Máx",
    "min": "Mín",
    "sum": "Suma",
    "changes": "Actualizar",
    "task": "Tarea",
    "notification": "Notificacion",
    "created": "Creado",
    "wf_sig": "Firma",
    "ed_gr": "Filas de texto para mostrar",
    "ed_ba": "Audio de fondo",
    "ed_map_zoom": "Zoom en mapa",
    "ed_map_source": "Fuente del mapa",
    "ed_map_style": "Estilo del mapa",
    "ed_round": "Número de decimales",
    "ed_hidden": "Ocultar en formulario",
    "ed_extendable": "Extensible",
    "ed_selfie": "Iniciar cámara en modo selfie",
    "ed_new": "Requiere que la foto sea tomada",
    "ed_read_nfc": "Leer un tag NFC en vez de código de barras",
    "ed_gt_0": "Debe ser mayor de cero o no establecerse.",
    "ed_add_to": "Adjuntar a pregunta",
    "ed_app": "Colocar en apéndice",
    "ed_barcode": "Mostrar como código de barras",
    "ed_si": "Mostrar imágenes de selección en lugar de etiquetas",
    "ed_stretch": "Estire las imágenes para ocupar todo el espacio asignado",
    "ed_hyperlink": "Mostrar el hipervínculo a la imagen",
    "ed_col_width": "ancho de columna %s1",
    "ed_place_map": "Permitir al usuario seleccionar la ubicación en el mapa",
    "ed_l_bold": "Etiqueta en negrita",
    "ed_caps": "Colocar etiqueta en mayúsculas",
    "ed_npb": "Nueva página antes",
    "ed_sa": "Espacios arriba",
    "ed_bgc": "Color de fondo de la etiqueta",
    "ed_vbgc": "Color de fondo del valor",
    "ed_mc": "Color del marcador",
    "ed_height": "Altura permitida para la respuesta",
    "ed_lw": "Ancho de etiqueta",
    "ed_pdfcols_help": "El total de ancho de todas las columnas debe sumar hasta 10",
    "ed_pdf_layout": "Diseño del PDF",
    "ed_pdfno": "Ocultar pregunta en pdf estándar",
    "ed_date_type": "Tipo Fecha",
    "ed_select_type": "Tipo Selección",
    "ed_nc": "No mostrar Calendario",
    "ed_my": "Mes y Año",
    "ed_bikram": "Bikram Sambat",
    "ed_coptic": "Coptico",
    "ed_ethiopian": "Etiope",
    "ed_islamic": "Islámico",
    "ed_myanmar": "Myanmar",
    "ed_persian": "Persa",
    "ed_r": "Calificación",
    "ed_bear": "Brújula",
    "ed_sep": "Separador de miles",
    "ed_sn": "Mostrar teclado numérico",
    "ed_numb_cols": "Número de columnas",
    "ed_min": "Mínimo",
    "ed_adv": "Avance automático",
    "ed_ac": "Autocompletar",
    "ed_acm": "Auto completar mínimo",
    "ed_compact": "Compacto",
    "ed_compact_adv": "Compacto con avance automático",
    "ed_image_map": "Mapa de imágen (SVG)",
    "ed_pick": "Selector de Números",
    "ed_as": "Agregar Búsqueda",
    "ed_rf": "Grupo de repetición de referencia",
    "ed_in": "Nombre Instancia",
    "ed_io": "Orden de registros",
    "ed_ic": "Número de registros",
    "ed_ep": "Proyecto Existente",
    "ed_es": "Formulario Existente",
    "ed_qt": "Texto de Pregunta",
    "ed_dn": "Nombre en cabecera",
    "ed_ct": "Pregunta de Selección",
    "ed_qh": "Texto de Ayuda",
    "ed_cl": "Lista de Selección",
    "ed_appearance": "Apariencia",
    "ed_parameters": "Parámetros",
    "ed_con": "Restricción",
    "ed_con_msg": "Mens. Restricción",
    "ed_sct": "Guardar cambios antes de ejecutar traducción automática",
    "ed_rel": "Relevancia",
    "ed_req": "Obligatorio",
    "ed_req_msg": "Mensaje obligatorio",
    "ed_nreq": "Opcional",
    "ed_ap": "Auto play",
    "ed_al": "Anotar automáticamente",
    "ed_mat": "Tipo de audio médico",
    "ed_mat_c": "Conversación",
    "ed_mat_d": "Dictado",
    "ed_al2": "Úselo en formularios de supervisión para anotar o traducir automáticamente texto, imágenes, audio y video",
    "ed_am": "Médico",
    "ed_am2": "Uso en transcripciones de audio que contenga términos médicos",
    "ed_at": "Precisión del GPS",
    "ed_ls": "Form. Enlazado",
    "ed_ro": "Sólo Lectura",
    "ed_ls_add": "Adicionar enlace",
    "ed_l": "Enlazado",
    "ed_nl": "No Enlazado",
    "ed_r_msg": "Mensaje de Texto Requerido",
    "ed_r_expression": "Expresión opcional para hacer que esta pregunta sea obligatoria",
    "ed_r_readonly": "Expresión opcional para que esta pregunta sea de solo lectura",
    "ed_f_l": "Se debe especificar en Parámetros el formulario a iniciarse.",
    "ed_emp_rep": "Los subformularios (grupos de repetición) y grupos deben tener al menos una pregunta.",
    "ed_hrk": "Llave Única",
    "ed_dk": "Llave de Datos",
    "ed_csv": "Archivo CSV",
    "ed_csvs": "Archivos CSV",
    "ed_c_s": "Fuente de Opciones",
    "ed_p_q": "Pregunta fuente",
    "ed_cws": "Hoja choices",
    "ed_i_c": "Creado",
    "ed_st": "Tabla Compartida",
    "ed_ld": "Permitir Importar Datos",
    "ed_pd": "Extraer datos de otro formulario diligenciado",
    "ed_i_bo": "Basado en",
    "ed_i_tn": "Nombres de Tablas",
    "ed_tlf": "Todos",
    "ed_namedia": "Archivo multimedia no se puede usar en esta pregunta",
    "ed_ab": "Agregar Antes",
    "ed_aa": "Agregar Después",
    "ed_aq": "Agregar Nueva Pregunta",
    "ed_ancl": "Agregar nueva lista de selección",
    "ed_anc": "Agregar Nueva Opción",
    "ed_cs": "Selección por Cascada",
    "ed_cspq": "Pregunta de Selección Previa",
    "ed_csp": "Selección Previa",
    "ed_cf": "Filtro Personalizada",
    "ed_afc": "Agregar Columna de Filtro",
    "ed_clabs": "Etiquetas de selección",
    "ed_clab": "Etiqueta de Opción",
    "ed_cval": "Opción",
    "ed_fv": "Valor del Filtro",
    "ed_sfv": "Segundo filtro de valor",
    "ed_choice_f": "Filtro de Opción",
    "ed_vc": "Nombres en lista de selección  deben contener sólo letras, números, guiones, guión al pisos, espacios y puntos. ",
    "ed_vq": "El nombre de la pregunta debe empezar con una letra, guión bajo o dos puntos y sólo puede contener letras, números, guión bajo, guión y punto",
    "ed_ns": "Agregue un Nuevo Formulario usando el menú 'Archivo -> Nuevo' antes de adicionar preguntas",
    "ed_kp": "Política de Llave",
    "ed_s1": "Selección Única",
    "ed_s": "Selección Múltiple",
    "ed_image": "Imagen",
    "ed_image_type": "Tipo Imagen",
    "ed_int": "Entero",
    "ed_gps": "Punto GPS",
    "ed_calc": "Cálculo",
    "ed_s_calc": "Cálculo en Servidor",
    "ed_ci": "Imagen PDF compuesta ",
    "ed_cm": "Mapa compuesto",
    "ed_audio": "Audio",
    "ed_video": "Video",
    "ed_bc": "Código de Barras",
    "ed_dt": "Fecha y Hora",
    "ed_t": "Hora",
    "ed_dec": "Decimal",
    "ed_gps_line": "Línea GPS",
    "ed_gps_area": "Area GPS",
    "ed_ack": "Confirmación",
    "ed_range": "Rango",
    "ed_graph": "Gráfica",
    "ed_qs": "Establecer Preguntas",
    "ed_ee": "No incluir preguntas sin respuestas en PDF nativo ",
    "ed_cpdf": "Comprimir PDF (las imágenes tendrán una resolución más baja que debería ser adecuada para imprimir)",
    "ed_er": "No se puede guardar hasta que se corrijan todos los errores",
    "ed_blocked": "El formulario esta desactivado. Los cambios no pueden ser guardados. Se debe activar nuevamente el formulario en la página de administración de formularios.",
    "ed_cml": "No puede modificar los idiomas mientras hayan cambios sin guardar",
    "ed_cx": "No se puede exportar un Formulario XLS mientras hayan cambios sin guardar",
    "ed_csr": "No puede establecer todas las preguntas obligatorias, u opcionales mientras haya cambios sin guardar",
    "ed_fi": "Identificador",
    "ed_dl": "Idioma",
    "ed_td": "Auditar tiempo en respuestas",
    "ed_rl": "Auditar ubicación de respuestas",
    "ed_rc": "Auditar cambios en respuestas",
    "ed_hod": "Ocultar el formulario en dispositivos",
    "ed_sld": "Buscar datos locales, no enviados, en el dispositivo",
    "ed_s_g": "Cuadricula",
    "ed_s_p": "Páginas",
    "ed_c_sr": "Todas las preguntas han sido establecidas como <span style=\"color:blue;\">obligatorias</span>",
    "ed_c_snr": "Todas las preguntas han sido establecidas como <span style=\"color:red;\">opcionales</span>",
    "ed_c_del_q": "Pregunta eliminada",
    "ed_c_del_o": "Selección %s1 eliminada de la Lista de Selección %s2",
    "ed_c_chg_p": "Propiedad %s1  de la pregunta %s2 cambiada de: %s4 a: %s3 ",
    "ed_c_add_q": "Pregunta %s1 agregada  con tipo %s2",
    "ed_c_add_o": "Selección %s1 añadida a Lista de Selección: %s2",
    "ed_c_settings": "Ajustes cambiados",
    "ed_c_languages": "Idiomas cambiados",
    "ed_c_template": "Se cambió la plantilla PDF",
    "ed_a_template": "Se agregó una plantilla PDF ",
    "ed_d_template": "Se eliminó la plantilla PDF",
    "ed_s_templates": "Las plantillas PDF añadidas mediante el cuadro de diálogo de configuración no se pueden configurar como \"no disponible\" ni como predeterminadas",
    "ed_mmf": "Archivos multimedia para este formulario",
    "ed_sl": "Formulario a iniciar",
    "ed_sc": "Formulario para completar",
    "ed_slu": "Formulario referenciado",
    "ed_gsi": "Obtener ID del formulario",
    "ed_qk": "Pregunta donde se almacena la llave retornada",
    "ed_qkc": "Pregunta en el formulario iniciado donde se guardará la llave de este formulario.",
    "ed_pl": "Diseño de Página",
    "ed_w": "Ancho en grilla de Form. Web",
    "ed_m": "Filtrar",
    "ed_fc": "Columna de Filtro",
    "ed_sfc": "Columna de Segundo Filtro",
    "ed_addcalc": "Agregar cálculo aquí",
    "contains": "Contiene",
    "startsWith": "Empieza con",
    "endsWith": "Finaliza con",
    "ed_ds": "Formulario de Datos",
    "ed_os": "Formulario de Supervisión",
    "ed_mr": "Solo permita que un enumerador acceda a sus propios datos mediante las funciones search() o pulldata(). Los datos enviados por otros usuarios no se descargarán como datos de referencia.",
    "ed_nb": "Sin Botones",
    "ed_offline": "Offline y Online",
    "ed_online": "Sólamente online",
    "ed_csa": "cambios aplicados satisfactoriamente",
    "ed_csf": "los cambios fallaron",
    "ed_transd": "Traducción efectuada de %s1 a %s2",
    "ed_ow": "Sobreescribir traducciones existentes",
    "ed_fe": "Expresión de filtro",
    "ed_e": "Expresión",
    "ed_drl": "Logo en PDF nativo",
    "ed_voice": "Sólo voz",
    "ed_na": "No disponible",
    "mf_id": "Incluir eliminados",
    "mf_cc": "Incluir casos cerrados",
    "mf_fd": "Datos del Formulario",
    "mf_md": "Datos de Supervisión",
    "mf_sc": "Mostrar Controles",
    "mf_sc_i": "Seleccione las columnas que quiera visualizar en la tabla y luego presione el botón 'Aplicar'. Las columnas se pueden ordenar posteriormente.",
    "mf_qr": "Columnas QR",
    "mf_bc_i": "Seleccione las columnas que usted desea ver como códigos de barras en la tabla y en reportes",
    "mf_st": "Seguimiento",
    "mf_gr": "Obtener relacionados",
    "mf_of": "Formulario de Supervisión",
    "mf_no": "No hay formularios de supervisión. Se pueden adicionar en la pestaña \"Formularios de Supervisión Disponibles\"",
    "mf_sel": "Seleccione el formulario a supervisar y el formulario de supervisión para usar con el primero.",
    "mf_ao": "Formularios de supervisión disponibles",
    "mf_mf": "Formularios de Supervisión",
    "mf_ld": "Detalles de Capa",
    "mf_tr": "Se requiere un Titulo",
    "mf_sr": "Informe Resumido",
    "mf_lock": "Bloquear para editar",
    "mf_rel": "Desbloquear",
    "mf_mr": "Mis registros",
    "mf_ur": "Registros sin asignar",
    "mf_or": "Otros registros",
    "mf_max": "Max registros",
    "mf_clear": "Borrar vista de registro único",
    "mf_hc": "Ocultar Controles",
    "mf_ts": "Ajustes de tabla",
    "ut_mps": "Separación máxima de puntos para incluir en una sola línea",
    "ut_mps_err": "La separación máxima de puntos debe ser mayor que 0",
    "lo_out": "Se ha desconectado de",
    "lo_lo": "Sesión Finalizada",
    "lo_loa": "Debe cerrar su navegador para asegurarse de que se eliminen los detalles de inicio de sesión almacenados en caché",
    "u_other_msg": "Esta configuración se aplica a la organización actual",
    "u_show_u": "Mostrar usuarios con permisos de",
    "u_show_p": "Mostrar usuarios en proyecto",
    "u_show_r": "Mostrar usuarios con rol",
    "u_show_o": "Mostrar usuarios con organización",
    "u_add": "Crear Usuario",
    "u_del": "Eliminar Usuario",
    "u_mv": "Mover a Organización",
    "u_cms": "Ajustes de gestión de casos",
    "u_mv_ent": "Mover a Empresa",
    "u_add_p": "Crear Proyecto",
    "u_del_p": "Eliminar Proyecto",
    "u_add_o": "Crear Organización",
    "u_del_o": "Eliminar Organización",
    "u_add_e": "Agregar Empresa",
    "u_del_e": "Borrar Empresa",
    "u_add_r": "Agregar Rol",
    "u_add_s": "Agregar ajuste",
    "u_edit_r": "Editar Rol",
    "u_del_r": "Eliminar Rol",
    "u_det": "Detalles del Usuario",
    "u_ident": "Usuario (minúsculas, sin espacios o un correo electrónico)",
    "u_email": "Enviar e-mail a nuevo usuario",
    "u_set_p": "Establecer contraseña",
    "u_sg": "Permisos",
    "u_det_p": "Detalles del Proyecto",
    "u_det_ur": "Detalles del Rol",
    "u_det_o": "Detalles de la Organización",
    "u_det_e": "Detalles de la Empresa",
    "u_det_o_rep": "Opciones de Publicación de Reportes",
    "u_det_o_ft": "Opciones en aplicación móvil",
    "u_det_o_wf": "Opciones de Form. Web",
    "u_det_pbc": "Color de fondo de la página",
    "u_det_paperbc": "Color de fondo del formulario",
    "u_det_buttonbc": "Color del botón",
    "u_det_buttontc": "Colores del texto del botón",
    "u_det_headertc": "Colores de encabezado de texto",
    "u_det_fp": "Posición de pié de página (en pixeles desde la derecha)",
    "u_wf_hd": "Ocultar la casilla de verificación \"Guardar como borrador\"",
    "u_ft_del": "Borrar datos enviados en el celular",
    "u_ft_prev_track_dis": "Evitar que se deshabilite el rastreo GPS",
    "u_ft_img_size": "Tamaño de las fotos almacenadas",
    "u_ft_img_camera": "Tamaño original de la cámara",
    "u_ft_im": "Método de entrada para Linea GPS o Area GPS",
    "u_ft_im_pt": "Ubicar puntos con toque en mapa",
    "u_ft_im_man": "Registro manual de ubicación",
    "u_ft_im_auto": "Registro automático de ubicación",
    "u_ri": "Intervalo de registro",
    "u_ft_vs": "Muy pequeña (640px)",
    "u_ft_s": "Pequeña (1024px)\n",
    "u_ft_m": "Mediana (2048px)",
    "u_ft_l": "Grande (3072px)",
    "u_ft_ld": "Enviar datos del recorrido del usuario (Rastreo)",
    "u_ft_os": "Habilita opciones de Enviar, Borrar, Editar y Nuevos formularios.",
    "u_ft_am": "Habilitar Menú de Administración",
    "u_ft_ex": "Deshabilitar opción Salir",
    "u_ft_bgs": "Evitar que se deshabilite el audio de fondo",
    "u_ft_in": "Permitir especificar el nombre de instancia",
    "u_ft_mf": "Habilitar Marcar el formulario como no finalizado (Guardar Borrador)",
    "u_ft_rv": "Permite la edición de formularios finalizados.",
    "u_ft_as": "Sincronizar Automáticamente",
    "u_ft_ms": "Sincronización Manual",
    "u_ft_sw": "WIFI",
    "u_ft_hrv": "Video HD",
    "u_ft_sw_c": "WIFI y datos del móvil",
    "u_ft_sop": "Establecer en teléfono",
    "u_ft_tasks": "Número máximo de tareas a mostrar",
    "u_ft_back_nav": "Retroceder en Preguntas",
    "u_ft_nav": "Navegación en pantalla",
    "u_ft_pw_timeout": "Número de días antes de que la contraseña expire ",
    "u_ft_pw_policy": "Política de Contraseñas",
    "u_ft_never": "Nunca pedir autenticación",
    "u_ft_always": "Siempre pedir autenticación al iniciar la aplicación",
    "u_ft_periodically": "Requiere autenticarse periodicamente",
    "u_ft_swipes": "Use deslizamiento horizontal",
    "u_ft_buttons": "Use los botones adelante/atrás",
    "u_ft_swipes_buttons": "Use deslizar y botones",
    "u_ft_sa": "Si - mostrar siempre",
    "u_ft_sc": "Si - colapsado",
    "u_ft_ss": "Habilitar el menú de configuración del servidor",
    "u_ft_md": "Habilitar el menú de  usuario y metadatos",
    "u_ft_eg": "Habilitar Geocerca (Tareas)",
    "u_det_o_email": "Opciones de Email",
    "u_det_o_other": "Otras Opciones",
    "u_det_o_limits": "Limite de uso mensual",
    "u_other_edit": "Permitir edición de los resultados",
    "u_email_tasks": "Permitir envío de tareas por Email",
    "u_use_api": "Permitir acceso a las API",
    "u_submissions": "Permitir envío de formularios",
    "u_notifications": "Permitir notificaciones",
    "u_sms": "Permitir SMS",
    "u_ratelimit": "Número máximo de solicitudes de API por minuto por organización",
    "u_mb_k": "Clave MapBox",
    "u_mb_a": "Cuenta Mapbox",
    "u_mb_s": "Id Estilo Mapbox",
    "u_g_k": "Clave Google Maps",
    "u_mt_k": "Llave de API  MapTiler",
    "u_smtp": "Servidor",
    "u_e_dom": "Dominio del Email",
    "u_e_nm": "Usuario Email",
    "u_e_si": "Identificador del Servidor",
    "u_e_p": "Password del Email",
    "u_e_port": "Puerto del servidor Email",
    "u_h_e": "Email para obtener ayuda",
    "u_rap": "Acceso restringido",
    "u_rap_d": "Administradores sólo pueden asignar los usuarios seleccionados a este proyecto",
    "u_chg": "Cambiado por",
    "u_usage": "Reporte de Uso",
    "u_attendance": "Reporte de Actividad",
    "u_notification": "Reporte de Notificaciones",
    "u_access": "Reporte de Acceso a Formularios",
    "u_r_u": "Reporte de Uso de Recursos Compartidos",
    "u_sms_url": "Servicio SMS",
    "u_sens_data": "Datos Sensibles",
    "u_sens_ao": "Sólo Admin",
    "u_sens_sq": "Preguntas de firma",
    "u_sens_nr": "Sin restricciones",
    "u_org_admin": "Administrador de la Organización",
    "u_ent_admin": "Administrador de la Empresa",
    "u_server_owner": "Propietario del Servidor",
    "u_check_mv_p": "Esta seguro de mover los siguientes proyectos (%s1) a %s2",
    "u_check_mv_o": "Esta seguro de mover la organización \"%s1\" a la empresa \"%s2\"",
    "u_only_one_ent": "Una sóla empresa ha sido creada. Se requiere al menos otra para mover la organización allá",
    "u_co": "Organización actual",
    "u_gr": "Descargar reporte",
    "u_sat": "Establecer como tema",
    "u_bl": "Logo del banner en form. webs (Altura 50px)",
    "u_ml": "Logo Principal",
    "u_nbc": "Color de la barra de navegación",
    "u_nbtc": "Color del texto de la barra de navegación",
    "u_eoi": "Habilitar Opt in",
    "admin": "Admin. Usuarios",
    "analyst": "Gestión de Formularios, Análisis y Tareas",
    "enterprise admin": "Admin. Nivel Empresas",
    "enum": "Captura de Datos Móvil y Web",
    "manage": "Consola - Formularios de Supervisión",
    "org admin": "Admin. Nivel Organizaciones",
    "security": "Gestión de Roles",
    "view data": "Análisis - Sólo Visualizar Datos",
    "manage tasks": "Gestión de Tareas",
    "view own data": "Sólo Visualizar Datos Propios (API)",
    "dashboard": "Tablero de Datos",
    "links": "Seguir enlaces (Biometría)",
    "u_css_f": "Archivo CSS",
    "u_css": "Cargar una hoja de estilos CSS",
    "u_css_ss": "Cargar una nueva hoja de estilos CSS para el servidor",
    "u_css_ss_org": "Cargar una nueva hoja de estilos CSS para la organización actual",
    "u_css_del": "Eliminar la hoja de estilos CSS",
    "u_css_sel": "Seleccionar una hoja de estilos",
    "u_css_info": "Cree una hoja de estilo personalizada utilizando <a href='https://themestr.app/theme' target='_blank'>este sitio web</a> y luego cárguela al servidor",
    "u_clear_p": "Borrar los proyectos vacios importados ya existentes",
    "u_clear_u": "Borrar los usuarios importados ya existentes",
    "u_clear_r": "Borrar los roles importados ya existentes",
    "u_api_rl": "Límite de frecuencia para la API de datos",
    "u_api_rlm": "Número mínimo de milisegundos entre solicitudes de datos de API. Cualquier solicitud recibida menos de este tiempo desde la solicitud anterior será rechazada. Se aplica a las solicitudes de datos json y csv. Cuanto menor sea el número, mayor será el volumen de solicitudes de API permitidas.",
    "u_mps": "Nivel de seguridad mínimo de la contraseña",
    "br_ci": "Indiferente a Mayúsculas y Minúsculas",
    "br_exact": "Coincidencia Exacta",
    "br_cc": "Selecciona las columnas a evaluar por similitudes en los datos. Por cada columna a evaluar se puede seleccionar una función para ampliar el rango de valores que deben coincidir",
    "br_s": "Buscar",
    "br_sdx": "Soundex",
    "br_cd": "Use la tabla de datos para esta vista de formulario",
    "br_tf": "Para preguntas de texto, incluyendo select y select_one",
    "br_nf": "Para preguntas numéricas, incluyendo enteros y decimales",
    "sr_res": "Archivos multimedia",
    "sr_nfc": "Lista de Tags NFC",
    "sr_uid": "UID (Identificador único) del tag NFC",
    "sr_geo": "Ubicación geográfica",
    "ar_af": "Agregar Archivos",
    "sr_g": "Grupo",
    "sr_fn": "Nombre de Archivo",
    "sr_m_ph": "Ingrese un nombre para su mapa",
    "sr_m_d": "Ingrese una descripción para este mapa (opcional)",
    "sr_m_mb": "Para Mapbox esto identifica el mapa, por ejemplo: mapbox/light-v10",
    "sr_cr": "Reportes Personalizados",
    "sr_al": "Usar ubicación anónima en Tarea",
    "sr_ul": "Actualizar ubicación existente",
    "sr_nl": "Guardar como Nueva Ubicación",
    "sr_sl": "Guardar Ubicación",
    "sr_sm": "Archivos de medios de formularios",
    "sr_si": "Las coordenadas NFC UID y GPS que especifique aquí se pueden guardar como una ubicación con nombre o usarse en la tarea como una ubicación anónima.",
    "sr_rh": "Histórico de recursos subidos",
    "ar": "Arabe",
    "en": "Inglés",
    "fr": "Francés",
    "hi": "Hindú",
    "pt": "Portugués",
    "es": "Español",
    "n_wf": "Formulario Web",
    "n_pdfp": "PDF (Vertical)",
    "n_pdfl": "PDF (Horizontal)",
    "n_eq": "Pregunta de Email",
    "n_ep": "Metadato con Email",
    "n_smsq": "Pregunta con Numero SMS",
    "n_share": "Enlace Web",
    "n_cs_e": "Lista de correos electrónicos separada por comas",
    "n_ea": "Dirección de Correo Electrónico",
    "n_eqc": "Pregunta que contendrá la dirección de correo electrónico a usar",
    "n_uiqc": "Pregunta que contendrá el id del usuario a notificar",
    "n_esc": "Asunto para el correo electrónico (Opcional)",
    "n_inc_ref": "Incluir formularios referenciados",
    "n_lo": "Incluir sólo datos capturados de los formularios que fueron activados por éste formulario",
    "task_reminder": "Recordatorio de tareas",
    "submission": "Registro",
    "console_update": "Actualización en Consola",
    "n_p": "Enviar recordatorio después",
    "n_oa": "Email original asignado",
    "n_ap": "Agregar marcador de posición",
    "n_si": "Id de remitente del SMS",
    "n_sms_n_tt": "Lista de números telefónicos separados por comas en formato ccnnnnnnnnnn",
    "n_sms_q_tt": "Pregunta que contendrá los números a enviar el SMS",
    "n_e_p_tt": "Meta item or dato precargado que contiene el email a usar",
    "n_uq": "Pregunta de actualización",
    "n_uv": "Valor de actualización",
    "n_no_oversight": "No hay formularios de supervisión para actualizar los datos en la consola",
    "n_nv": "Se debe especificar un valor para actualizar",
    "n_nq": "Se debe especificar  una pregunta apara actualizar",
    "n_curl": "URL de retrollamada",
    "n_aa": "Después de la alerta %s1.",
    "n_as": "Asignar formulario %s1 a %s2.",
    "n_dow": "Día de la semana",
    "n_dom": "Día del mes",
    "n_sent": "Notificación enviada",
    "ro_fr": "Filtrar Filas",
    "ro_fc": "Filtrar Columnas",
    "ro_fr_rule": "Filas a mostrar",
    "ro_aq": "Preguntas disponibles",
    "ro_fr_i": "Ingrese una regla que determine cuales filas serán mostradas para este rol. Encierre los nombres de preguntas en ${...}. Encierre el texto en comillas simples.  Asegure que haya espacios entre los nombres y los operadores tales como =. <br/>Ejemplo 1: ${region} = 'norte'<br/>Ejemplo 2: ${edad} > 16. Si ninguna regla regla se especifica todas las filas se mostrarán.",
    "ro_fc_i": "Seleccione las columnas a mostrar con este filtro. Si no selecciona ninguna columna, todas serán mostradas.",
    "ro_transform": "Transformación de Datos",
    "i_m": "minutos",
    "i_h": "horas",
    "i_d": "dias",
    "i_sec": "hace un segundo",
    "i_secs": "segundos atrás",
    "i_min": "hace un minuto",
    "i_mins": "minutos atrás",
    "i_hour": "hace una hora",
    "i_hours": "horas atrás",
    "i_day": "hace un día",
    "i_days": "días trás",
    "d_sound": "Activar sonido en nueva alerta",
    "d_rep_def_freq": "Frecuencia del reporte",
    "bar_h": "Gráfico de Barras Horizontal",
    "bar_v": "Gráfico de Barras Vertical",
    "stacked": "Apilado",
    "normalized": "Normalizado",
    "pie": "Gráfico de Torta",
    "line": "Gráfico de Líneas",
    "wordcloud": "Nube de Palabras",
    "length": "Cuenta",
    "d_qtr": "25%",
    "d_half": "50%",
    "d_3qtr": "75%",
    "d_full": "100%",
    "d_sec": "Segundos",
    "d_min": "Minutos",
    "d_hour": "Horas",
    "d_day": "Días",
    "d_c_day": "Conteo por días",
    "d_c_month": "Conteo por mes",
    "d_c_year": "Conteo por Año",
    "d_add": "Adicionar",
    "d_add_c": "Agregar Gráfico",
    "d_add_q": "Agregar Nueva Consulta",
    "d_add_f": "Agregar Nuevo Formulario",
    "d_from_f": "Enlazar desde Formulario",
    "d_from_q": "Enlazar desde Pregunta",
    "d_edit_web": "Editar en Formulario Web",
    "d_d_pdf": "Descargar Reporte PDF",
    "d_layers": "Cambiar Mapa",
    "rev_upd_diff": "Actualizar una pregunta diferente a la pregunta original",
    "rev_sel_pk": "Seleccionar datos a cambiar usando la llave primaria (record)",
    "rev_q_upd": "Pregunta a actualizar",
    "rev_text": "Texto",
    "rev_upd": "Actualizar",
    "rev_upd_t": "Actualizar pregunta objetivo",
    "rev_upd_text": "Actualizar Texto de Preguntas",
    "rev_rt": "Reemplazar texto",
    "rev_rc": "Registros con opciones",
    "rev_fq": "desde pregunta",
    "rev_rw": "registros con",
    "rev_rdm": "Revisar Modificaciones de Datos",
    "rev_ci": "Cambiar Id",
    "rev_rb": "Reversado por",
    "rev_cb": "Modificado por",
    "rev_rcn": "Reversar Numero de Cambio",
    "rev_det": "Detalles del número de cambio",
    "rev_cq": "Pregunta Cambiada",
    "rev_sc": "Opción Seleccionada",
    "rev_usc": "Opción No seleccionada",
    "ch_ds": "Datos del Gráfico",
    "quantity": "Cantidad",
    "free": "Gratis",
    "unitCost": "Costo Unitario",
    "amount": "Cantidad",
    "server": "Servidor",
    "submissions": "Registros",
    "submissions_i": "Un límite de cero es ilimitado.",
    "disk": "Disco",
    "rekognition": "AWS Rekognition",
    "rekognition_i": "Imágenes",
    "sentiment": "Servicio AWS Comprehend",
    "sentiment_i": "solicitudes",
    "translate": "Traducción usando el servicio AWS",
    "translate_i": "letras",
    "transcribe_medical": "AWS Transcripción Médica",
    "transcribe_medical_i": "segundos de audio",
    "transcribe": "Transcripción usando el servicio AWS",
    "transcribe_i": "segundos de audio",
    "static_map": "Mapas estáticos de Mapbox",
    "google_static_map": "Mapa estático de Google",
    "maptiler_static_map": "Mapa estático de MapTiler",
    "monthly": "Cargo mensual",
    "org_bill_rpt": "Uso por Organización",
    "bill_enable": "Habilitar facturación",
    "bill_from": "Aplica desde",
    "bill_chg_date": "Fecha de Actualización",
    "bill_norates": "No se ha establecido tarifas para %s1. Si ha habilitado facturación, entonces se aplicarán las tarifas definidas para %s2",
    "billing_disabled_msg": "Se ha deshabilitado la facturación",
    "rep_usage_project": "Uso por proyecto",
    "rep_usage_survey": "Uso por formulario",
    "rep_usage_device": "Uso por dispositivo",
    "rep_values_question": "Pregunta de Valores",
    "rep_values": "Valores",
    "rep_wide_columns": "Columnas a lo ancho",
    "rep_msg_min_keys": "Se debe especificar mínimo una pregunta llave si la transformación está habilitada.",
    "rep_msg_v_q": "Se debe especificar las preguntas de valores, si la transformación está habilitada.",
    "rep_msg_min_values": "Se debe especificar mínimo un valor si la transformación está habilitada.",
    "rep_msg_min_wc": "Se debe especificar mínimo una wide column, si la transformación está habilitada.",
    "rep_ch": "Encabezado de Columna",
    "rep_inc_temp": "Incluir usuarios temporales",
    "rep_inc_alltime": "Incluir datos para 'todo el tiempo' así como el mes seleccionado",
    "rep_gen": "Reportes Generados",
    "rep_gen_ov": "Los reportes generados por un proceso en segundo plano se pueden descargar desde aquí. Se conservarán durante 2 semanas y luego se eliminarán automáticamente.",
    "locations_distance": "Distancia recorrida",
    "locations_kml": "KML",
    "rep_au": "Incluir todos los usuarios en el proyecto",
    "rep_d": "Tiempo de generación (segundos)",
    "rep_my": "Año y mes del reporte",
    "co_dd": "Desglosar",
    "co_up": "Arriba",
    "co_tid": "Incluir valor de texto en Descarga",
    "co_b": "Cambio masivo",
    "mo_anon": "Anónimo",
    "mo_ce": "Borrar correos existentes sin enviar ",
    "mo_ns": "No se ha seleccionado un Correo Masivo",
    "mo_na": "Sin Autorización",
    "mo_nf": "El formulario no fué encontrado",
    "mo_ss": "Este formulario ha sido enviado satistactoriamente",
    "mo_exp": "Este formulario ha expirado",
    "mo_del_done": "Este formulario ha sido borrado",
    "mo_se": "Error del sistema",
    "mo_del": "¿Está seguro de que desea eliminar el correo\"%s1\"? Los destinatarios a los que ya se les hayan enviado correos electrónicos ya no podrán responder.",
    "mo_blocked": "Este formulario esta desactivado. Intente más tarde o contacte al administrador para activarlo de nuevo.",
    "mo_import": "Importar Emails",
    "mo_export": "Exportar Emails",
    "mo_subject": "Asunto:",
    "mo_content": "Mensaje:",
    "mo_sent": "Enviado",
    "mo_sd": "Detalles del estado",
    "mo_ms": "Envíos múltiples",
    "mo_send": "¿Estás seguro de que estás listo para enviar los correos electrónicos?",
    "mo_gen": "¿Está seguro de que desea generar los enlaces ahora? Se crean automáticamente cuando usa el botón de correo electrónico no enviado, sin embargo, puede generarlos ahora si desea enviarlos a través de un canal diferente. Para los enlaces de envío único, una vez creados, caducarán en 30 días.",
    "mo_oi": "Los siguientes mensajes de suscripción han sido enviados y están esperando una respuesta.",
    "svc_at": "Traducción automática",
    "svc_from_l": "De Idioma",
    "svc_to_l": "A idioma",
    "log_hr": "Resúmen de eventos",
    "log_sd": "Detalles del formulario",
    "li_success": "Inicio de sesión exitosa",
    "li_failure": "Fallo de inicio de sesión",
    "li_continue": "Volver a aplicaciones",
    "cm_fs": "Estatus final",
    "cm_sq": "Pregunta de estatus",
    "cm_cq": "Pregunta de criticidad",
    "cm_aa": "Agregar una alerta",
    "cm_dcms": "Ya existe un evento de gestión de casos con ese nombre para este grupo de formularios",
    "cm_alert_a": "Alerta si no se finaliza dentro de",
    "cm_a": "Alerta de gestión de casos",
    "cm_bar": "Barra",
    "cm_col": "Columna",
    "cm_pie": "Torta",
    "cm_alert": "Alerta de gestión de casos",
    "cm_ns": "Seleccione un formulario para ver los datos del caso",
    "cm_oc": "Conteo de casos abiertos y cerrados por día",
    "cm_p": "Mostrar datos del último",
    "cm_7days": "7 días",
    "cm_14days": "14 días",
    "cm_30days": "30 días",
    "cm_areq": "Se debe especificar una pregunta de estado y un valor de estado final si está utilizando alertas.",
    "fp_nm": "No se encontraron coincidencias",
    "pw_gen": "Generar contraseña",
    "pw_mm": "La contraseña y su confirmación no son las mismas",
    "ss_title": "Estado del servidor"
});