define(
{
    "m_home": "Inicio",
    "m_admin": "Administración",
    "m_tm": "Formularios",
    "m_analysis": "Análisis",
    "m_reports": "Reportes",
    "m_reports_def": "Reportes por Defecto",
    "m_reports_org": "Reportes de Organización",
    "m_reports_leg": "Reportes Formato Anterior",
    "m_reports_new": "Nuevo Reportes",
    "m_refresh": "Actualizar",
    "m_export": "Exportar",
    "m_export_media": "Exportar con Imágenes",
    "m_discuss": "Discusión",
    "m_modify": "Modificar",
    "m_data_mod": "Form. Web",
    "m_web_forms": "Form. Web",
    "m_docs": "Documentación",
    "m_monitor": "Monitoreo",
    "m_user": "Usuarios",
    "m_assign": "Tareas",
    "m_query": "Consultas",
    "m_help": "Ayuda",
    "m_forgot_password": "Recuperar Contraseña",
    "m_register": "Registrarse",
    "m_locations": "Rastreo",
    "m_section": "Sección",
    "m_notify": "Notificaciones",
    "m_view": "Ver",
    "m_attach": "Cargar adjuntos",
    "m_modules": "Modulos",
    "m_open": "Abrir",
    "m_new": "Nuevo",
    "m_import": "Importar",
    "m_calculations": "Cálculos",
    "m_resources": "Recursos Compartidos",
    "m_review": "Revisión",
    "m_mf": "Formularios Supervisados",
    "m_br": "Ver Datos",
    "m_manage": "Supervisión",
    "m_dash": "Tablero de Datos",
    "m_s_m_f": "Configurar Form. Supervisados",
    "m_task_m": "Gestión de Tareas",
    "m_user_profile": "Perfil de Usuario",
    "m_login": "Ingresar",
    "m_logs": "Sesiones",
    "m_info": "Información",
    "m_os": "Supervisión",
    "m_billing": "Consumos",
    "m_billing_server": "Por Servidor",
    "m_billing_orgs": "Por Organización",
    "ss_welcome": "Bienvenido al Servidor Versión:",
    "ss_welcome2": "Cambios en la versión",
    "ss_ft": "Obtener App móvil",
    "ss_su": "Obtener el Cargador Smap",
    "c_apply": "Aplicar",
    "c_desc": "Descripción",
    "c_default": "Por Defecto",
    "c_project": "Proyecto",
    "c_forms": "Formularios Activos",
    "c_form": "Formulario",
    "c_forward": "Otra Cuenta",
    "c_forwarded": "Reenviados a otro servidor",
    "c_name": "Nombre",
    "c_company_name": "Empresa",
    "c_company_addr": "Dirección Comercial",
    "c_company_phone": "Teléfono Corporativo",
    "c_company_email": "Email Corporativo",
    "c_type": "Tipo",
    "c_file": "Archivo",
    "c_host": "Servidor",
    "c_user": "Usuario",
    "c_projects": "Proyectos",
    "c_email": "Email",
    "c_sms": "SMS",
    "c_document": "Document",
    "c_twitter": "Twitter",
    "c_lang": "Idioma",
    "c_langs": "Idiomas",
    "c_pulldata": "Pulldata",
    "c_orientation": "Orientación",
    "c_password": "Contraseña",
    "c_c_p": "Confirmar Contraseña",
    "c_r_p": "Cambiar Contraseña",
    "c_en": "Activar",
    "c_loc_f": "Form. Local:",
    "c_rem_f": "Form. Remoto",
    "c_rem_u": "Usuario Remoto",
    "c_enabled": "Activado",
    "c_edit": "Editar",
    "c_del": "Eliminar",
    "c_del_data": "Borrar Datos",
    "c_res_data": "Restaurar Datos",
    "c_download": "Descargar",
    "c_upload": "Subir",
    "c_done": "Realizado",
    "c_cancel": "Cancelar",
    "c_save": "Guardar",
    "c_saved": "Guardado",
    "c_submit": "Enviar",
    "c_submitted": "Datos Enviados",
    "c_test": "Verificar",
    "c_validate": "Validar",
    "c_close": "Cerrar",
    "c_logout": "Cerrar Sesión",
    "c_block": "Desactivar",
    "c_blocked": "Desactivado",
    "c_graph": "Gráfica",
    "c_map": "Mapa",
    "c_chart": "Gráfico",
    "c_charts": "Gráficos",
    "c_maps": "Mapas",
    "c_map_layers": "Cambiar Mapa",
    "c_table": "Tabla",
    "c_tables": "Tablas",
    "c_images": "Imágenes",
    "c_title": "Titulo",
    "c_comment": "Comentario",
    "c_country": "País",
    "c_region": "Región",
    "c_district": "Departamento",
    "c_community": "Ciudad",
    "c_node": "Nodo",
    "c_relation": "Relación",
    "c_from": "De",
    "c_subject": "Asunto",
    "c_to": "A",
    "c_properties": "Propiedades",
    "c_question": "Pregunta",
    "c_questions": "Preguntas",
    "c_choices": "Opciones",
    "c_include": "Incluir",
    "c_unique": "Unico",
    "c_survey": "Formulario",
    "c_date": "Fecha",
    "c_dateq": "Pregunta con Fecha",
    "c_none": "Ninguno",
    "c_period": "Período",
    "c_hour": "Hora",
    "c_day": "Día",
    "c_week": "Semana",
    "c_month": "Mes",
    "c_year": "Año",
    "c_matches": "Coincidencias",
    "c_filter": "Filtrar",
    "c_inclusive": "Inclusive",
    "c_value": "Valor",
    "c_clear": "Limpiar",
    "c_options": "Opciones",
    "c_data": "Datos",
    "c_layers": "Capas",
    "c_settings": "Ajustes",
    "c_start": "Inicia",
    "c_back": "Atras",
    "c_target": "Destino",
    "c_content": "Contenido",
    "c_today": "Hoy",
    "c_attach": "Adjunto",
    "c_details": "Detalles",
    "c_action": "Acción",
    "c_actions": "Acciones",
    "c_mapid": "Id. del Mapa",
    "c_zoom": "Niveles de Zoom",
    "c_zoom_data": "Zoom a Datos",
    "c_vector_data": "Datos del Vector",
    "c_vector_style": "Estilo del Vector",
    "c_style": "Estilo",
    "c_portrait": "Vertical",
    "c_landscape": "Horizontal",
    "c_tools": "Herramientas",
    "c_required": "Establecer todas como Obligatorias",
    "c_not_required": "Establecer todas como Opcionales",
    "c_del_sel": "Eliminar Seleccionada",
    "c_print": "Imprimir",
    "c_repeat": "Repetición",
    "c_repeats": "Repeticiones",
    "c_scheduled": "Programada",
    "c_t_c": "Términos y condiciones",
    "c_agree": "Estoy de acuerdo con",
    "c_select": "Seleccionar",
    "c_status": "Estatus",
    "c_coords": "Coordenadas",
    "c_task": "Tarea",
    "c_rec": "(Recomendado)",
    "c_source": "Fuente",
    "c_show": "Mostrar",
    "c_hide": "Ocultar",
    "c_total": "Total",
    "c_totals": "Totales",
    "c_instances": "Registros",
    "c_device": "Dispositivo",
    "c_success": "Exitosos",
    "c_errors": "Errores",
    "c_error": "Error",
    "c_warning": "Advertencia",
    "c_lt": "Hora Local",
    "c_simserial": "Número de SIM Card",
    "c_location": "Ubicación",
    "c_ident": "ID",
    "c_version": "Version",
    "c_deleted": "Eliminado",
    "c_yes": "Si",
    "c_no": "No",
    "c_reason": "Razón",
    "c_complete": "Completo",
    "c_record": "Registro",
    "c_records": "Registros",
    "c_of": "de",
    "c_media": "Multimedia",
    "c_changes": "Cambios",
    "c_meta": "Metadatos",
    "c_calc": "Cálculos",
    "c_trans": "Traducir",
    "c_org": "Organización",
    "c_orgs": "Organizaciones",
    "c_all_s": "Todos",
    "c_event": "Evento",
    "c_note": "Nota",
    "c_server": "Servidor",
    "c_cols": "Columnas",
    "c_add": "Adicionar",
    "c_create": "Crear",
    "c_generate": "Generar",
    "c_imp_xls": "Importar Formulario XLS (Excel)",
    "c_xlstype": "Formato Excel",
    "c_roles": "Roles",
    "c_s_roles": "Roles en Formularios",
    "c_role": "Rol",
    "c_id": "Id",
    "c_insert": "Insertar",
    "c_tz": "Zona Horaria",
    "c_undef": "Sin Definir",
    "c_license": "Numero de Licencia",
    "c_in": "En",
    "c_rev": "Reverso",
    "c_for": "Para",
    "c_normal": "Normal",
    "c_heatmap": "Mapa de Calor",
    "c_auth": "Autorizado",
    "c_merge": "Combinar",
    "c_discard": "Descartar",
    "c_keys": "Llaves",
    "c_counts": "Conteos",
    "c_unsav": "Tiene cambios no guardados. Esta seguro que quiere salir?",
    "c_off": "Desactivado",
    "c_on": "Activado",
    "c_replace": "Reemplazar",
    "c_retry": "Reintentar",
    "c_alink": "Link Anónimo",
    "c_excel": "Excel",
    "c_csv": "CSV",
    "c_osm": "Openstreetmap",
    "c_shape": "Shape",
    "c_kml": "KML / KMZ",
    "c_vrt": "VRT / CSV",
    "c_stata": "Stata / CSV",
    "c_spss": "SPSS / CSV",
    "c_pdf": "PDF",
    "c_phone": "Teléfono",
    "c_rep_type": "Repetición",
    "c_cl": "Copiar Hipervínculo",
    "c_cb": "Copiar a Portapapeles",
    "c_c": "Copiado",
    "c_quantity": "Cantidad",
    "c_after": "Después",
    "c_units": "Unidades",
    "c_duration": "Duración",
    "c_msg": "Mensaje",
    "c_completed": "Realizada",
    "c_unsubscribed": "Darse de baja",
    "c_unsubscribe": "Darse de baja",
    "c_subscribe": "Suscribirse",
    "c_unsent": "Email no fué enviado",
    "ft": "Tipo de Archivo",
    "ft_xls": "Archivo XLS Form",
    "ft_xls_orig": "Archivo XLS Original",
    "ft_xml": "Formato XML",
    "ft_codebook": "Especificaciones del Formulario",
    "ft_pdf": "Plantilla PDF",
    "ft_spss": "Archivo SPS (SPSS)",
    "tm_s_del": "Mostrar formularios eliminados",
    "tm_d_forms": "Eliminar Formularios",
    "tm_r_forms": "Recuperar Formularios",
    "tm_e_forms": "Borrar Formularios",
    "tm_c_form": "Crear Un Formulario",
    "tm_c_form_rep": "Reemplazar un formulario",
    "tm_c_xls": "Usando un formulario XLS (Excel)",
    "tm_g_temp": "Descargar Plantilla",
    "tm_g_new": "Nuevo Formulario",
    "tm_g_open": "Abrir un Formulario",
    "tm_g_temp_i1": "Descarga una plantilla para crear un nuevo formulario. Cuando haya terminado, podrá subirlo al servidor haciendo click en el botón de abajo, seleccionando el archivo XLS que contiene el formulario y asignarle el nombre correspondiente",
    "tm_g_temp_i3": "Guía de Referencia",
    "tm_ul_f": "Cargar Formulario XLS (Excel)",
    "tm_si": "Especifique el Identificador del formulario",
    "tm_up": "Subir Plantilla",
    "tm_ups": "Cargar Formulario",
    "tm_add_for": "Agregar Adelante",
    "tm_ref_f": "Actualizar Lista de Formularios",
    "tm_o_u": "Ir a Versión Anterior",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccione un formulario",
    "a_exp_leg2": "Formato de Salida:",
    "a_exp_notes": "Exportar Notas:",
    "a_exp_meta": "Incluir Meta Datos:",
    "a_exp_split": "Separar Coordenadas:",
    "a_exp_merge": "Comprimir Selecciones Múltiples:",
    "a_sel_ways": "Seleccionar modos (si tiene):",
    "a_sel_forms": "Seleccionar las tablas a incluir:",
    "a_sel_query": "No hay consultas para exportar. Usted necesitará crear una usando el menu consultas en el modulo de tablero de datos (Dashboard)",
    "a_sel_model": "Editar Modelo de Formulario",
    "a_type": "Tipo de Gráfico",
    "a_showon": "Mostrar sobre",
    "a_ss": "Seleccionar Formulario",
    "a_sq": "Seleccionar pregunta",
    "a_gb": "Agrupar por",
    "a_ts": "Series de Tiempo",
    "a_sl": "Mostrar etiqueta",
    "a_g_gps": "Coordenadas GPS dentro de región",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Desde Fecha",
    "a_to_date": "Hasta Fecha",
    "a_fq": "Filtrar pregunta",
    "a_res": "Por favor suministre una razón",
    "a_mb": "Marcado Erróneo",
    "a_oo": "de",
    "a_cm": "Miembros de Cluster",
    "a_dv": "Mostrar Detalles",
    "a_rd": "Definición de Reporte",
    "a_rp": "Parámetros del Reporte",
    "a_embed": "Colocar las Imágenes en las celdas del archivo Excel",
    "a_hxl": "HXL",
    "a_query": "Seleccione una consulta",
    "a_fn": "Función",
    "a_ni": "Se requiere habilitar \"Permitir Importar Datos\" para este formulario desde Ajustes  en el editor de formularios.",
    "a_nx": "XLSX Nuevo",
    "a_lx": "XLS Anterior",
    "a_lh": "HTML Anterior",
    "msg_pk_sel": "Sólo puede seleccionar el registro si ha marcado \"Actualizar una pregunta diferente\"",
    "msg_wait": "Esperando respuesta del servidor. Por favor intente de nuevo en unos segurndos",
    "msg_reason": "Por favor suministre una razón:",
    "msg_sel_survey": "Se debe seleccionar un formulario",
    "msg_sel_dates": "Fecha Inicial es mayor que Fecha Final",
    "msg_sel_q": "Se debe seleccionar una pregunta para mostrar en la grafica",
    "msg_val_prot": "Se debe especificar un protocolo (http:// or https://) con el nombre del servidor",
    "msg_val_p": "Se debe seleccionar un proyecto para este formulario",
    "msg_val_rf": "Se debe seleccionar un formulario remoto",
    "msg_val_rh": "Debe seleccionar un servidor remoto",
    "msg_val_u_id": "Debe especificar un Id de usuario",
    "msg_val_pass": "Debe especificar una contraseña",
    "msg_nv": "Por favor especifique un nuevo valor",
    "msg_val_nm": "Se requiere un nombre",
    "msg_val_ad": "Si asigna una tarea utilizando los datos recopilados, debe especificar los datos",
    "msg_val_ad2": "El rol adicional debería ser especificado sólamente si el primer rol fué especificado",
    "msg_val_file": "Se debe seleccionar un archivo",
    "msg_val_let": "El nombre debe empezar con una letra o guion al piso",
    "msg_pwd_l": "Contraseñas, si son especificadas, deben contener mínimo 1 caracter.",
    "msg_pwd_m": "Constraseñas no coinciden",
    "msg_add_notification": "Agregar Notificación",
    "msg_edit_notification": "Editar Notificación",
    "msg_nn": "Sin Notificaciones",
    "msg_add_map": "Agregar Mapa",
    "msg_edit_map": "Editar Mapa",
    "msg_sel_form": "Seleccione Tabla:",
    "msg_sel_media": "Seleccionar Pregunta Multimedia",
    "msg_sel_media_f": "Seleccionar Archivo Multimedia",
    "msg_err_save": "Error: NO se pudo Guardar:",
    "msg_err_del": "Error:  NO se pudo Eliminar:",
    "msg_err_cr": "Error: En Creación",
    "msg_err_upd": "Error en cargue:",
    "msg_err_res": "Error: NO se pudo Restaurar:",
    "msg_err_block": "Error: NO se pudo Inhabilitar:",
    "msg_err_get_f": "Error: Fallo en carga de formularios:",
    "msg_err_get_r": "Error: Fallo en lectura de roles",
    "msg_err_get_a": "Error: Fallo en recibo de Alertas",
    "msg_err_get_q": "Error: Fallo en cargue de preguntas",
    "msg_err_get_s": "Error: Error trayendo formularios",
    "msg_upd": "Actualización Exitosa",
    "msg_err_nc": "Nombre no puede incluir una coma",
    "msg_err_wait": "Esperando conexión con servidor  o no hay formularios en este proyecto para asignar a un usuario. Si el proyecto tiene respuestas reintente en pocos segundos.",
    "msg_err_cert": "El servidor remoto no tiene una firma digital válida. Intente usar http:// en vez de https://",
    "msg_no_edit_rep": "No se puede editar un registro que ha sido reemplazado por otro registro",
    "msg_confirm_del": "Esta seguro que quiere eliminar",
    "msg_confirm_tasks": "este grupo y todas sus tareas?",
    "msg_del_r": "Esta seguro de eliminar estas regiones?",
    "msg_erase": "Esta seguro de eliminar de manera permanente estos formularios y todo los datos asociados?",
    "msg_restore": "Esta seguro de restaurar estos formularios borrados?",
    "msg_del_recs": "Hay %s1 registros de datos del formulario %s2. Está seguro de eliminar estos datos?",
    "msg_del_s": "Está seguro de eliminar estos formularios?",
    "msg_del_data": "Está seguro de eliminar todos los datos en este formulario?",
    "msg_del_groups": "Este formulario es parte de un grupo y si borra sus datos, también se borrarán los datos de los otros formularios relacionados.",
    "msg_res_data": "Esta seguro de querer restaurar todos los datos de este formulario a los datos enviados originales?",
    "msg_del_data2": "Está seguro?",
    "msg_del_rep": "Está seguro de eliminar este reporte?",
    "msg_del_users": "Está seguro de eliminar estos usuarios?",
    "msg_del_projects": "Está seguro de eliminar estos proyectos?",
    "msg_del_roles": "Esta seguro de eliminar estos roles?",
    "msg_del_orgs": "Está seguro de eliminar estas organizaciones?",
    "msg_del_q": "Está seguro de eliminar esta pregunta?",
    "msg_del_cl": "Está seguro de eliminar esta lista de selección?",
    "msg_del_c": "Está seguro de borrar esta opción de selección?",
    "msg_rep_f": "Esta seguro de reemplazar el filtro de selección",
    "msg_n_v": "Inválido",
    "msg_u_f": "Error de fallo en subida de archivo",
    "msg_u_nt": "No se encontraron tags NFC",
    "msg_csv": "Sólo archivos CSV y ZIP conteniendo archivos CSV o multimedia son permitidos",
    "msg_inv_email": "No es un e-mail válido",
    "msg_dup_email": "Email duplicado. Otro usuario tiene este correo electrónico",
    "msg_email_req": "Si esta enviando un email al usuario entonces debe especificarse",
    "msg_email_dom": "Nombre de usuario de Email no debe incluir el dominio. Asi para una direccion como ejemplo.org, el nombre de usuario debería ser 'ejemplo'",
    "msg_dup_ident": "Usuario duplicado. Favor cambiar el usuario",
    "msg_cs": "Toque para filtrar u ordenar en esta columan",
    "msg_nrf": "No hay resultados direccionados a otro servidor",
    "msg_saf": "Seleccionar un formulario y ver que usuarios lo han descargado",
    "msg_nf": "No hay formularios",
    "msg_ns": "No hay enviados",
    "msg_us": "Fuente Desconocida",
    "msg_tg_ns": "No se ha seleccionado un Grupo de Tareas",
    "msg_tg_rd": "La regla del grupo de tareas se ha borrado",
    "msg_no_roles": "No hay roles habilitados. Por ende no hay restricciones en acceso.",
    "msg_has_roles": "Sólo los usuarios que tengan uno de los siguientes roles habilitados pueden tener acceso.",
    "msg_one_f": "Se debe seleccionar mínimo un formulario",
    "msg_one_f2": "Se debe seleccionar un formulario",
    "msg_embed": "El tipo excel debe ser xls o xlsx para incluir imágenes en las celdas",
    "msg_pss": "Por favor seleccione un formulario",
    "msg_nm": "No se encontraron archivos multimedia",
    "msg_pr": "Se ha restablecido la contraseña",
    "msg_es": "Se ha enviado email a",
    "msg_refresh": "Se han realizado algunos cambios y éstos no se han guardado aún, está seguro de actualizar sin guardar?",
    "msg_leave": "Se han realizado algunos cambios y éstos no se han guardado aún, está seguro de salir sin guardar?",
    "msg_test": "Se deben realizar algunos cambios y deben guardarse antes de realizar pruebas con el formulario",
    "msg_not_f": "no fué encontrado",
    "msg_ren": "renombrado a",
    "msg_nq": "No se tienen consultas definidas, use el botón \"Agregar Consulta\" para adicionar una",
    "msg_dup_f": "Este formulario ya está en la consulta",
    "msg_ui": "No se permiten espacios en el usuario",
    "msg_sp": "Seleccionar un proyecto para ver el estatus de los formularios",
    "msg_ab_ns": "Se debe seleccionar agregar tareas desde datos ya enviados o agregar tareas de datos a ser enviados o ambos.",
    "msg_n1": "emails en una pregunta",
    "msg_n2": "emails en metadatod",
    "msg_sms_n1": "Enviar SMS a",
    "msg_sms_n2": "números ingresados en respuesta a una pregunta",
    "msg_ds_s": "Descarga iniciada. Si son muchos reportes, tomará algún tiempo..",
    "msg_survey_replaced": "Formulario reemplazado",
    "msg_survey_loaded": "Formulario cargado",
    "msg_reg": "Registro aceptado. Un email ha sido enviado a %s1 con el enlace para establecer su contraseña",
    "msg_uns": "Dado de baja satisfactoriamente",
    "msg_s1": "Un email se ha enviado a la dirección de correo electrónico suministrada. Haga click en el enlace para confirmar su suscripción.",
    "msg_s2": "Suscripción realizada exitosamente",
    "e_b_e": "Crear desde un formulario existente",
    "e_s_r": "Almacenar datos en tabla compartida  con datos origen",
    "t_complete": "Mostrar Tareas Completadas",
    "t_show": "Mostrar tareas por:",
    "t_assign_type": "Tipo de Asignación",
    "t_assign": "Asignar a Usuario",
    "t_assign_roles": "Asignar a usuarios con rol",
    "t_fixed_role": "Y este rol",
    "t_add_group": "Adicionar Grupo de Tareas",
    "t_del_group": "Eliminar Grupo de Tareas",
    "t_edit_group": "Ver Ajuste de Grupo de Tareas",
    "t_lt_file": "Cargar Tareas desde Archivo",
    "t_choose_user": "Escoja el usuario para asignar la tarea seleccionada",
    "t_ce": "Borrar Datos Existentes",
    "t_ce_warn": "Esto borrará todos los datos existentes del formulario. Seguro que quiere hacer esto?",
    "t_ceg": "Crear Grupo de Tareas Vacio",
    "t_cfe": "Crear desde datos existentes",
    "t_ep": "Proyecto Existente",
    "t_es": "Formulario Existente",
    "t_ec": "Selección Existente",
    "t_et": "Texto Existente",
    "t_nt": "Nuevo Texto",
    "t_ns": "Nuevo Formulario",
    "t_ft": "Filtro de Tareas",
    "t_aft": "Filtro Avanzado",
    "t_df": "Filtro de Fechas",
    "t_fq": "Filtrar por Pregunta",
    "t_so": "Opción Seleccionada",
    "t_sn": "Establecer Valor Numérico",
    "t_st": "Establecer Valor de Texto",
    "t_ue": "Actualizar Resultados Existentes",
    "t_ap": "Campo de Dirección (Visible en Línea 3 de Tareas)",
    "t_nfc": "NFC o Ubicación",
    "t_assigned": "Asignada a:",
    "t_fl": "Archivo cargado",
    "t_tl": "Plantilla Cargada",
    "t_efnl": "Error archivo no cargado",
    "t_ens": "Error No Guardado",
    "t_add_tasks": "Haga click en el mapa donde se quiera adicionar tareas. Cuando termine haga click en botón 'Guardar Tareas'",
    "t_add_task": "Agregar Tarea",
    "t_edit_task": "Editar Tarea",
    "t_add_tasks2": "Agregar Tareas",
    "t_save_tasks": "Guardar Tareas",
    "t_tasks_only": "No mostrar formularios en dispositivo móvil (Sólo tareas)",
    "t_tg": "Grupo de Tareas",
    "t_tasks": "Tareas",
    "t_id": "Datos Iniciales",
    "t_n_s": "Tareas sin fecha de inicio",
    "t_drag": "Arrastre una tarea y agréguela al calendario",
    "t_g": "Guía",
    "t_ass_done": "Ha terminado esta asignación?",
    "t_defn": "Definición de Grupo de Tareas",
    "t_au": "Todos los usuarios",
    "t_u": "Sin asignar",
    "t_ad": "Asignar desde valores de datos",
    "t_af": "Crear tareas de resultados enviados después de crear el grupo de tareas",
    "t_ac": "Crear tareas de resultados que ya han sido enviados",
    "t_start": "Ajuste el tiempo de inicio y duración de la tarea relativos a cuando fue creado o a una pregunta de fecha",
    "new": "Sin asignar",
    "accepted": "Asignada a:",
    "submitted": "Completo",
    "rejected": "Rechazada",
    "cancelled": "Cancelada",
    "deleted": "Eliminado",
    "e_u_err": "Error en cargue de formulario",
    "e_u_exists": "existe en proyecto",
    "e_h_rename": "Cambie el nombre del formulario o elimine el formulario anterior",
    "e_u_sm_no_list": "pregunta tipo selección múltiple (select_multiple) sin lista de nombres",
    "e_h_sm_no_list": "Revise el archivo .xls del formulario. Compruebe que haya una lista de nombres para todas las preguntas de selección múltiple (select_multiple)",
    "e_u_so_no_list": "pregunta tipo selección única (select_multiple) sin lista de nombres",
    "e_h_so_no_list": "Revise el archivo .xls del formulario. Compruebe que exista una lista de nombres para todas las preguntas de selección única (select_one)",
    "e_unknown": "Error desconocido",
    "e_get_help": "Contacte la mesa de ayuda:  contacto@kontrolid.com",
    "e_calc": "Error en cálculo",
    "e_h_calc1": "Revise la columna 'calculation' si hay una formula inválida (Una formula válida da como resultado verdadero (true) o falso (false))",
    "e_h_calc2": "Si no revise la columna 'relevant' si alguna formula no da como resultado true o false",
    "e_inv_f": "Función inválida",
    "e_h_f1": "Revise si hay letras mayúsculas. Todas las letras deben estar en minúsculas",
    "e_h_f2": "Revise errores de escritura en el nombre de la función",
    "e_val": "Error de Validación",
    "e_circ": "Revise por referencias circulares",
    "e_in_q": "en pregunta",
    "e_h_c1": "Una declaración 'relevant´en una pregunta se está refiriendo a ella misma en vez de a otra pregunta.",
    "e_h_c2": "Declaraciones relevantes se están evaluando antes de una pregunta que si es ejecutada no podrá referirse a sus propias preguntas.",
    "e_brackets": "Falta cerrar corchetes en una función",
    "e_text": "Error en el siguiente texto:",
    "r_o_n": "Organización",
    "r_y_n": "Nombre",
    "r_y_e": "Email",
    "r_y_o": "Sitio web",
    "r_f": "Formulario de Registro",
    "r_s": "Suscripciones",
    "mon_l200": "(últimos 200)",
    "mon_gtb": "Agrupar Totales por",
    "mon_nl": "No cargado",
    "mon_ue": "Errores en Subida",
    "mon_dup": "Duplicados",
    "mon_att": "Con Adjuntos Extra",
    "mon_sa": "Mostrar como",
    "mon_zoom_grid": "Zoom a Cuadrículas",
    "mon_show_grid": "Mostrar Cuadrículas",
    "mon_clear_grid": "Limpiar Cuadrículas",
    "mon_create_grid": "Crear Cuadrículas",
    "mon_del_grid": "Eliminar Cuadrículas",
    "mon_sel_layer": "Seleccionar un capa adicional para mostrar sobre mapa.",
    "mon_c_reg": "Crear una nueva región",
    "mon_c_reg_i": "Ingrese un nombre para la región y el ancho de las celdas en metros. Haga click en el mapa para fijar el centro de las celdas. Presione la tecla mayúsculas) y arrastre el ratón para fijar los límites.",
    "mon_name_cond": "(minúsculas, sin espacios o números)",
    "mon_cw": "Ancho de Celda (in Metros. mayor que 10)",
    "mon_centre": "Centrar: (Haga clic en mapa)",
    "mon_bounds": "Límites: (haga clic y arrastre en el mapa mientras presiona la tecla de mayúsculas",
    "mon_sel_del": "Seleccione las regiones que quiere eliminar",
    "mon_ud": "Fecha de Subida",
    "mon_pi": "IMEI del Dispositivo",
    "mon_fr": "Causa del Fallo:",
    "mon_file": "Archivo de datos",
    "error": "Error",
    "success": "Exitosos",
    "an_auth": "Autor",
    "an_published": "Publicado",
    "an_publish": "Publicar",
    "an_dr": "Rango de Fechas",
    "an_csel": "Limpiar Selección",
    "r_add": "Agregar Reporte",
    "r_ed": "Editar Reporte",
    "r_del": "Eliminar Reportes",
    "an_nd": "No hay datos disponibles",
    "an_nmd": "No hay datos resultantes con este filtro",
    "an_mod_hint": "Esta página permite hacer cambios masivos en textos. Se puede seleccionar un valor de texto específico y los cambios se producirán en todas las ocurrencias al otro valor. Este es útil para hacer ajustes de errores de escritura. También se pueden cambiar valores de preguntas de selección cuando se han incluidos cajones de texto para \"Otro\". También es posible actualizar valores de códigos de barras o cálculos. Tipos de preguntas que no son soportadas son por ejemplo enteros. Se pueden revisar las modificaciones realizadas  seleccionando la página Revisión<br/><br/>  Se puede sin embargo, actualizar enteros, decimales y preguntas de selección marcando el botón de chequeo \"Actualizar una pregunta diferente a la pregunta original: \". En este caso los cambios aplicarán a todas las preguntas que conincidan con los valores existentes de las dos preguntas. En la mayoría de los casos no será necesario esta opción.",
    "Upload Time": "Subir",
    "_start": "Hora Inicio",
    "_end": "Hora Final",
    "percent": "Porcentaje",
    "count": "Conteo",
    "none": "Ninguno",
    "average": "Promedio",
    "max": "Máx",
    "min": "Mín",
    "sum": "Suma",
    "wf_sig": "Firma",
    "ed_in": "Nombre de Instancia",
    "ed_ep": "Proyecto Existente",
    "ed_es": "Formulario Existente",
    "ed_qt": "Texto de Pregunta",
    "ed_dn": "Nombre para Mostrar",
    "ed_ct": "Pregunta de Selección",
    "ed_qh": "Texto de Ayuda",
    "ed_cl": "Lista de Selección",
    "ed_appearance": "Apariencia",
    "ed_parameters": "Parámetros",
    "ed_con": "Restricción",
    "ed_con_msg": "Mens. Restricción",
    "ed_rel": "Relevancia",
    "ed_req": "Obligatorio",
    "ed_nreq": "Opcional",
    "ed_ap": "Auto play",
    "ed_at": "Precisión del GPS",
    "ed_ls": "Enlazar Form.",
    "ed_ro": "Sólo Lectura",
    "ed_ls_add": "Adicionar enlace",
    "ed_l": "Enlazado",
    "ed_nl": "No Enlazado",
    "ed_r_msg": "Mensaje de Texto Requerido",
    "ed_o_o_g": "Sólo una pregunta de geolocalización puede ser usada en un formulario",
    "ed_hrk": "Llave Única",
    "ed_dk": "Llave de Datos",
    "ed_csv": "Archivo CSV",
    "ed_c_s": "Fuente de Opciones",
    "ed_i_c": "Creado",
    "ed_st": "Tabla Compartida",
    "ed_ld": "Permitir Importar Datos",
    "ed_pd": "Extraer datos de otro formulario diligenciado",
    "ed_i_bo": "Basado en",
    "ed_i_tn": "Nombres de Tablas",
    "ed_tlf": "Todos",
    "ed_namedia": "Archivo multimedia no se puede usar en esta pregunta",
    "ed_ab": "Agregar Antes",
    "ed_aa": "Agregar Después",
    "ed_aq": "Agregar Nueva Pregunta",
    "ed_anc": "Agregar Nueva Opción",
    "ed_cs": "Selección por Cascada",
    "ed_cspq": "Pregunta de Selección Previa",
    "ed_csp": "Selección Previa",
    "ed_cf": "Filtro Personalizada",
    "ed_afc": "Agregar Columna de Filtro",
    "ed_clab": "Etiqueta de Opción",
    "ed_cval": "Opción",
    "ed_fv": "Valor del Filtro",
    "ed_choice_f": "Filtro de Opción",
    "ed_vc": "Nombres de opciones sólo puede tener letras, números, guiones, guión al piso y puntos",
    "ed_vq": "El nombre de la pregunta debe empezar con una letra, guión bajo o dos puntos y sólo puede contener letras, números, guión bajo, guión y punto",
    "ed_gl": "El nombre de una pregunta de localización (GPS) no se puede cambiar y debe ser \"the_geom\"",
    "ed_ogl": "Sólo las preguntas de localización (GPS) pueden tener el nombre \"the_geom\"",
    "ed_ns": "Agregue un Nuevo Formulario usando el menú 'Archivo -> Nuevo' antes de adicionar preguntas",
    "ed_kp": "Política de Llave",
    "ed_s1": "Selección Única",
    "ed_s": "Selección Múltiple",
    "ed_image": "Imagen",
    "ed_int": "Entero",
    "ed_gps": "Punto GPS",
    "ed_calc": "Cálculo",
    "ed_audio": "Audio",
    "ed_video": "Video",
    "ed_bc": "Código de Barras",
    "ed_dt": "Fecha y Hora",
    "ed_t": "Hora",
    "ed_dec": "Decimal",
    "ed_gps_line": "Línea GPS",
    "ed_gps_area": "Area GPS",
    "ed_ack": "Confirmación",
    "ed_range": "Rango",
    "ed_graph": "Gráfica",
    "ed_qs": "Establecer Preguntas",
    "ed_ee": "No incluir respuestas vacías en reporte PDF nativo",
    "ed_er": "No se puede guardar hasta que se corrijan todos los errores",
    "ed_blocked": "El formulario esta desactivado. Los cambios no pueden ser guardados. Se debe activar nuevamente el formulario en la página de administración de formularios.",
    "ed_cml": "No puede modificar los idiomas mientras hayan cambios sin guardar",
    "ed_cx": "No se puede exportar un Formulario XLS mientras hayan cambios sin guardar",
    "ed_csr": "No puede establecer todas las preguntas obligatorias, u opcionales mientras haya cambios sin guardar",
    "ed_fi": "Identificador del Formulario",
    "ed_dl": "Idioma por Defecto",
    "ed_td": "Registrar Tiempo de Respuestas",
    "ed_s_g": "Cuadricula (Forms Web)",
    "ed_s_p": "Pages",
    "ed_c_del_q": "Pregunta eliminada",
    "ed_c_del_o": "Selección %s1 eliminada de la Lista de Selección %s2",
    "ed_c_chg_p": "Propiedad %s1  de la pregunta %s2 cambiada de: %s4 a: %s3 ",
    "ed_c_add_q": "Pregunta %s1 agregada  con tipo %s2",
    "ed_c_add_o": "Selección %s1 añadida a Lista de Selección: %s2",
    "ed_c_settings": "Ajustes cambiados",
    "mf_fd": "Datos del Formulario",
    "mf_md": "Datos de Supervisión",
    "mf_sc": "Columnas Visibles",
    "mf_sc_i": "Seleccione las columnas que quiera visualizar en la tabla y luego presione el botón 'Aplicar'. Las columnas se pueden ordenar posteriormente.",
    "mf_qr": "Columnas QR",
    "mf_bc_i": "Seleccione las columnas que usted desea ver como códigos de barras en la tabla y en reportes",
    "mf_st": "Seguimiento",
    "mf_gr": "Obtener relacionados",
    "mf_of": "Formulario de Supervisión",
    "mf_no": "No hay formularios de supervisión. Se pueden adicionar en la pestaña \"Formularios de Supervisión Disponibles\"",
    "mf_sel": "Seleccione el formulario a supervisar y el formulario de supervisión para usar con el primero.",
    "mf_ao": "Formularios de supervisión disponibles",
    "mf_mf": "Formularios Supervisados",
    "mf_ld": "Detalles de Capa",
    "mf_tr": "Se requiere un Titulo",
    "mf_sr": "Informe Resumido",
    "lo_back": "Atras",
    "lo_out": "Se ha desconectado de",
    "lo_lo": "Sesión Finalizada",
    "u_show_u": "Mostrar usuarios con privilegio de",
    "u_show_p": "Mostrar usuarios en proyecto",
    "u_show_r": "Mostrar usuarios con rol",
    "u_add": "Crear Usuario",
    "u_del": "Eliminar Usuario",
    "u_mv": "Mover a Organización",
    "u_add_p": "Crear Proyecto",
    "u_del_p": "Eliminar Proyecto",
    "u_add_o": "Crear Organización",
    "u_del_o": "Eliminar Organización",
    "u_add_r": "Agregar Rol",
    "u_edit_r": "Editar Rol",
    "u_del_r": "Eliminar Rol",
    "u_det": "Detalles del Usuario",
    "u_ident": "Usuario (minúsculas, sin espacios o un correo electrónico)",
    "u_email": "Enviar e-mail a nuevo usuario",
    "u_set_p": "Establecer contraseña",
    "u_sg": "Privilegios",
    "u_det_p": "Detalles del Proyecto",
    "u_det_ur": "Detalles del Rol",
    "u_det_o": "Detalles de la Organización",
    "u_det_o_rep": "Opciones de Publicación de Reportes",
    "u_det_o_ft": "Opciones de Aplicación Móvil",
    "u_ft_del": "Borrar datos enviados en el celular",
    "u_ft_ld": "Enviar datos del recorrido del usuario",
    "u_ft_os": "Habilita el menú de Enviar, Borrar, Editar y Obtener nuevos formularios en la App Móvil",
    "u_ft_am": "Habilitar Menú de Administración",
    "u_ft_in": "Permitir al usuario especificar el nombre de instancia",
    "u_ft_rv": "Permite que los formularios finalizados puedan ser abiertos para revisión en la App Móvil",
    "u_ft_as": "Sincronizar Automáticamente",
    "u_ft_ms": "Sincronización Manual",
    "u_ft_sw": "WIFI",
    "u_ft_sw_c": "WIFI y datos del móvil",
    "u_ft_sop": "Establecer en teléfono",
    "u_ft_tasks": "Número máximo de tareas para descargar",
    "u_det_o_email": "Opciones de Email",
    "u_det_o_other": "Otras Opciones",
    "u_other_edit": "Permitir edición de los resultados",
    "u_mb_k": "Clave MapBox",
    "u_g_k": "Clave Google Maps",
    "u_smtp": "Servidor",
    "u_e_dom": "Dominio del Email",
    "u_e_nm": "Usuario Email",
    "u_e_p": "Password del Email",
    "u_e_port": "Puerto del servidor Email",
    "u_h_e": "Email para obtener ayuda",
    "u_rap": "Acceso restringido",
    "u_rap_d": "Administradores sólo pueden asignar los usuarios seleccionados a este proyecto",
    "u_chg": "Cambiado por",
    "u_usage": "Reporte de Uso",
    "u_sms_url": "Servicio SMS",
    "br_ci": "Indiferente a Mayúsculas y Minúsculas",
    "br_exact": "Coincidencia Exacta",
    "br_cc": "Selecciona las columnas a evaluar por similitudes en los datos. Por cada columna a evaluar se puede seleccionar una función para ampliar el rango de valores que deben coincidir",
    "br_s": "Buscar",
    "br_sdx": "Soundex",
    "br_cd": "Use la tabla de datos para esta vista de formulario",
    "br_tf": "Para preguntas de texto, incluyendo select y select_one",
    "br_nf": "Para preguntas numéricas, incluyendo enteros y decimales",
    "sr_res": "Archivos Multimedia y . CSV",
    "sr_nfc": "Lista de Tags NFC",
    "ar_af": "Agregar Archivos",
    "sr_g": "Grupo",
    "sr_fn": "Nombre de Archivo",
    "sr_m_ph": "Ingrese un nombre para su mapa",
    "sr_m_d": "Ingrese una descripción para este mapa (opcional)",
    "sr_m_mb": "Para MapBox esto identifica el mapa, por ejemplo: mapbox.light",
    "sr_cr": "Reportes Personalizados",
    "ar": "Arabe",
    "en": "Inglés",
    "fr": "Francés",
    "hi": "Hindú",
    "pt": "Portugués",
    "es": "Español",
    "n_wf": "Formulario Web",
    "n_pdfp": "PDF (Vertical)",
    "n_pdfl": "PDF (Horizontal)",
    "n_eq": "Pregunta de Email",
    "n_ep": "Metadato con Email",
    "n_smsq": "Pregunta con Numero SMS",
    "n_share": "Enlace Web",
    "n_cs_e": "Lista de correos electrónicos separada por comas",
    "n_ea": "Dirección de Correo Electrónico",
    "n_eqc": "Pregunta que contendrá la dirección de correo electrónico a usar",
    "n_esc": "Asunto para el correo electrónico (Opcional)",
    "ro_fr": "Filtrar Filas",
    "ro_fc": "Filtrar Columnas",
    "ro_fr_rule": "Filas a mostrar",
    "ro_aq": "Preguntas disponibles",
    "ro_fr_i": "Ingrese una regla que determine cuales filas serán mostradas para este rol. Encierre los nombres de preguntas en ${...}. Encierre el texto en comillas simples.  Asegure que haya espacios entre los nombres y los operadores tales como =. <br/>Ejemplo 1: ${region} = 'norte'<br/>Ejemplo 2: ${edad} > 16. Si ninguna regla regla se especifica todas las filas se mostrarán.",
    "ro_fc_i": "Seleccione las columnas a mostrar con este filtro. Si no selecciona ninguna columna, todas serán mostradas.",
    "i_m": "minutos",
    "i_h": "horas",
    "i_d": "dias",
    "i_sec": "hace un segundo",
    "i_secs": "segundos atrás",
    "i_min": "hace un minuto",
    "i_mins": "minutos atrás",
    "i_hour": "hace una hora",
    "i_hours": "horas atrás",
    "i_day": "hace un día",
    "i_days": "días trás",
    "d_sound": "Activar sonido en nueva alerta",
    "d_rep_def_freq": "Frecuencia del reporte",
    "bar_h": "Gráfico de Barras Horizontal",
    "bar_v": "Gráfico de Barras Vertical",
    "pie": "Gráfico de Torta",
    "line": "Gráfico de Líneas",
    "wordcloud": "Nube de Palabras",
    "length": "Cuenta",
    "d_qtr": "25%",
    "d_half": "50%",
    "d_3qtr": "75%",
    "d_full": "100%",
    "d_sec": "Segundos",
    "d_min": "Minutos",
    "d_hour": "Horas",
    "d_c_day": "Conteo por días",
    "d_c_month": "Conteo por mes",
    "d_c_year": "Conteo por Año",
    "d_add": "Adicionar",
    "d_add_c": "Agregar Gráfico",
    "d_add_q": "Agregar Nueva Consulta",
    "d_add_f": "Agregar Nuevo Formulario",
    "d_from_f": "Enlazar desde Formulario",
    "d_from_q": "Enlazar desde Pregunta",
    "d_edit_web": "Editar en Formulario Web",
    "d_d_pdf": "Descargar Reporte PDF",
    "d_layers": "Cambiar Mapa",
    "rev_upd_diff": "Actualizar una pregunta diferente a la pregunta original",
    "rev_sel_pk": "Seleccionar datos a cambiar usando la llave primaria",
    "rev_q_upd": "Pregunta a actualizar",
    "rev_text": "Texto",
    "rev_upd": "Actualizar",
    "rev_upd_t": "Actualizar pregunta objetivo",
    "rev_upd_text": "Actualizar Texto de Preguntas",
    "rev_rt": "Reemplazar texto",
    "rev_rc": "Registros con opciones",
    "rev_fq": "desde pregunta",
    "rev_rw": "registros con",
    "rev_rdm": "Revisar Modificaciones de Datos",
    "rev_ci": "Cambiar Id",
    "rev_rb": "Reversado por",
    "rev_cb": "Modificado por",
    "rev_rcn": "Reversar Numero de Cambio",
    "rev_det": "Detalles del número de cambio",
    "rev_cq": "Pregunta Cambiada",
    "rev_sc": "Opción Seleccionada",
    "rev_usc": "Opción No seleccionada",
    "ch_ds": "Datos del Gráfico",
    "quantity": "Cantidad",
    "free": "Gratis",
    "unitCost": "Costo Unitario",
    "amount": "Cantidad",
    "server": "Servidor",
    "submissions": "Registros",
    "disk": "Disco",
    "static map": "Mapas Estáticos",
    "rekognition": "AWS Rekognition",
    "org_bill_rpt": "Uso por Organización"
});