/*
 * This file is used by dynamic webforms generated by surveyMobileAPI.
 * It is not referenced by other files within the client module
 */

"use strict";

import localise from './app/localise.js';

var gUserLocale = navigator.language;
if (Modernizr.localstorage) {
    gUserLocale = localStorage.getItem('user_locale') || navigator.language;
}
window.gUserLocale = gUserLocale;

localise.initLocale(gUserLocale).then(function() {
        localise.setlang();
    });
